### ISSUE TITLE
Get all claims [3.0.1]

### ISSUE THREAD

**Issue by robrez** [auth0/java-jwt#116]
I was just upgrading from 2.2.1 and I can no longer find a way to get all claims... I see a signature to get a claim by name, but not one to get either the keyset or entire entryset... Did I miss something?

**Comment by XtreZz** [comment]
I have noticed that too,I need this feature.Will it be available ?

**Comment by hzalaz** [comment]
@robrez, @XtreZz what's the use case for getting all claims from a collection when you can do it from the object that is returned after decode/verify?

**Comment by robrez** [comment]
I have an API gateway that gets a token from an upstream service writes it
to a database  and returns a token identifier to the consumer (instead of
the token itself).

It also acts as the refresh token issuer. The code that exchanges a refresh
token for a new access token reads the old access token, copies all claims
to the new token except for iat and exp.

I think that, in general, since the older versions of the library returned
a Map, a lot of people may have been using things you can do with a map..
like enumeration.
