### ISSUE TITLE
Array claim [3.0.1]

### ISSUE THREAD

**Issue by chadjaros** [auth0/java-jwt#117]
I'm trying to update from 2.1.0 to 3.0.1, but it seems like it's illegal to add a claim which consists of an array of values. Is this intentionally restricted, and is that restriction present in the [RFC](https://tools.ietf.org/html/rfc7519)?

**Comment by chadjaros** [comment]
From the RFC:

    2. Terminology
    ...    
    Claim Value [Page 5]
        The value portion of a claim representation.  A Claim Value can be
        any JSON value.

It seems that Arrays and Maps should be allowed parameters in `JwtCreator#withClaim`

**Comment by hzalaz** [comment]
@chadjaros it can be added. If you want a faster turnaround please submit a PR and we'll review and merge

**Comment by lbalmaceda** [comment]
Available in version `3.1.0`.
