### ISSUE TITLE
Clock is package private [3.0.1]

### ISSUE THREAD

**Issue by chadjaros** [auth0/java-jwt#118]
Should the Clock class, and JWTVerifier#build method be public instead of package private? Making these package private doesn't do me any good if I want to use a custom clock for unit testing.

**Comment by chadjaros** [comment]
Related to #50

**Comment by hzalaz** [comment]
Might be a good idea. Will have to review the API to make this possible. PRs are always welcomed, we were busy handling other work but we'll try to be up to date with them

**Comment by lbalmaceda** [comment]
Available in version `3.1.0`.
