### ISSUE TITLE
 [PATCH] The LICENSE file is missing

### ISSUE THREAD

**Issue by jcodagnone** [auth0/java-jwt#122]
It never existed:
```

$ find -type f -name LICENSE
$ git log --stat|grep LICENSE
```

[0001-The-LICENSE-file-is-missing.patch.txt](https://github.com/auth0/java-jwt/files/649989/0001-The-LICENSE-file-is-missing.patch.txt)

**Comment by pose** [comment]
@jcodagnone https://github.com/auth0/java-jwt/blob/v2/LICENSE.txt this one? ;) it's in the old master branch

**Comment by hzalaz** [comment]
@jcodagnone thanks for heads up!
