### ISSUE TITLE
No way to extract complex set of claims

### ISSUE THREAD

**Issue by ensonik** [auth0/java-jwt#127]
Using the library, there is no way for me get a handle on the data contained in a "complex" claim. For example, I can't read the following:

```
{ 
  user_metadata: {
     client_id: "abc"
  }
}
```

Using `jwt.getClaim("user_metadata").asXXXXX` returns null in all cases.

Being able to get a handle on the raw JSON could do the trick, but that doesn't seem possible either. 

Suggestions?

**Comment by hzalaz** [comment]
Will be available once #123 is merged and released
