### ISSUE TITLE
JWT.getClaims() doesn't exists [3.0.2]

### ISSUE THREAD

**Issue by chbhernani** [auth0/java-jwt#129]
[Private Claims](https://github.com/auth0/java-jwt#private-claims-1) readme topic shown a method that doesn't exists. In fact, this one should be a very useful feature, but isn't present into current release.

**Comment by hzalaz** [comment]
@chbhernani a snippet with how you are trying to access the private claim(s) might help

**Comment by chbhernani** [comment]
Hi @hzalaz 

I'm trying like shown on readme. Find below the snippet.
```
String token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJpc3MiOiJhdXRoMCJ9.AbIJTDMFc7yUa5MhvcP03nJPyCPzZtQcGEp-zWfOkEE";
try {

    JWT jwt = JWT.decode(token);
    
    Map<String, Claim> claims = jwt.getClaims();
    Claim claim = claims.get("isAdmin");
    
} catch (JWTDecodeException exception){
    //Invalid token
}
```

When I try call jwt.getClaims() the compiler doesn't recognize this method, with this quickFix alert
`The method getClaims() is undefined for the type JWT`

**Comment by hzalaz** [comment]
@chbhernani and `getClaim(String)`?

**Comment by chbhernani** [comment]
@hzalaz this one there is. But I'm refering to getClaims(), like readme show.

**Comment by lbalmaceda** [comment]
Hi @chbhernani,
That feature was unreleased. Try with the fresh 3.1.0 release.

```
compile 'com.auth0:java-jwt:3.1.0'
```
Cheers.

**Comment by chbhernani** [comment]
Great!
Thank you guys @hzalaz @lbalmaceda!
