### ISSUE TITLE
Timestamps are limited by Integer/int to 2038-01-19T04:14:07.000+0100

### ISSUE THREAD

**Issue by larspettern** [auth0/java-jwt#132]
If the "expires at" claim is set to a date larger than 2038-01-19, then it gets broken by the fact that the date is translated into a int. See [PayloadSerializer line 58](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java)

The latest date possible to represent in seconds as a Java Integer is 

`new Date(Integer.MAX_VALUE * 1000L);`

Which corresponds to 2038-01-19T04:14:07.000+0100

The date claims should always be respresented as Long in Java since the second values will overflow the Integer max value and you will get an erroneous value.

This applies to the other timestamp claims also (issued at, and not before) together with the custom date claims.

**Comment by lbalmaceda** [comment]
@larspettern thanks for the report. I'll look into it 👍
