### ISSUE TITLE
Outdated Jar?

### ISSUE THREAD

**Issue by Gungrave223** [auth0/java-jwt#156]
Tried including jar in project...but the Algorithm class seems to be from an outdated version. Only have one constructor for RSA256 ... for v3.1.0

**Edit**
Nvm... Went back and checked the commit and saw that, that change was added 16 days ago and v3.1.0 was released back in January so guess that change won't be out til the next release...so will be looking forward to it =]

**Comment by lbalmaceda** [comment]
Hi @Gungrave223 
You must have downloaded the `3.0.1` jar. The latest version is `3.1.0` and it's not available in the releases tab, but you can find it in mavencentral and jcenter.

```groovy
compile 'com.auth0:java-jwt:3.1.0'
```

**Comment by Gungrave223** [comment]
Nope definitely v3.1.0....But I'm just assuming the changes made after Jan 4th haven't been released yet... specifically [#147](https://github.com/auth0/java-jwt/pull/147)

**Comment by lbalmaceda** [comment]
Yes, sorry for the confusion. The `KeyProvider` and `Public+Private keys` signatures hasn't been released yet. I hope to do it the next week. 👍 
Cheers

**Comment by Gungrave223** [comment]
Cool thanks 👍
