### ISSUE TITLE
Claim collection/array creation

### ISSUE THREAD

**Issue by pacey** [auth0/java-jwt#158]
version: 3.0.2

It looks like the library supports reading a claim as a collection/array but how can I create a JWT that has a collection/array claim?

If the library just doesn't support it that's a real shame as I am using the Auth0 Authorization extension which sets the users groups as a claim array. This makes it hard (impossible?) for me to test as I cannot create a similar JWT.

Are there any work arounds for this? I wouldn't mind submitting a PR if someone could point me in the right direction.

**Comment by lbalmaceda** [comment]
Hi @pacey 
Arrays are supported since version `3.1.0`.

```
String jwt = JWTCreator.init()
	                .withArrayClaim("name", new String[]{"text", "123", "true"})
	                .sign(Algorithm.HMAC256("secret"));
```

**Comment by pacey** [comment]
Cool, I'll explicitly specify that version in my project. It was coming transitively from `auth0-spring-security-api`, is it worth requesting the version be bumped in that project?
