### ISSUE TITLE
How do you create a Claim that is a collection?

### ISSUE THREAD

**Issue by rgibanez** [auth0/java-jwt#163]
I'm trying to create a Claim which will be called 'custom' and will be a collection of key/value pairs.

Example:

`"user_id": "123456",
  "custom": {
    "first_name": "John",
    "last_name": "Smith"
  }`

I can create the Claim: user_id, but am unsure of the best way to add the Claim which is a collection.

`String token = JWT.create().withClaim("user_id", "123456").sign(algorithm);`

Any advise would be great.

**Comment by lbalmaceda** [comment]
@rgibanez what you want to create is claims with Maps. That's not available and won't be at least for now. Check issues like https://github.com/auth0/java-jwt/issues/135

**Comment by rgibanez** [comment]
@lbalmaceda - thanks for the fast response - any rough time frame for this? Otherwise I'll have to look for another library :(

**Comment by lbalmaceda** [comment]
@rgibanez Unfortunately there's no ETA as we have other priorities right now. But we're looking into a solution that can include at least simple map support.
Cheers.

**Comment by mklnwt** [comment]
IMHO you should add the possibility to add a string as [RawValue](https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/util/RawValue.html).
That way we can serialize our object ourselves and still get a "pretty" output.

ATM if we add a string claim, it will be escaped and all quotation etc. starts with a backslash which is really annoying and can lead to problem with usage on consumer side.
