### ISSUE TITLE
.asLong() ?

### ISSUE THREAD

**Issue by dessalines** [auth0/java-jwt#168]
I have ID fields as `Long` in my DB, but noticed that the `.getClaim()` methods only have `asString()`, `.asInt()`, and `.asDouble()`. That can easily be converted, but an `.asLong()` helper method makes sense.

**Comment by lbalmaceda** [comment]
Hi @dessalines,
That's already merged and will be available on next release. https://github.com/auth0/java-jwt/pull/157
