### ISSUE TITLE
java-jwt\scripts\release.gradle' line: 156 

### ISSUE THREAD

**Issue by lafredi** [auth0/java-jwt#169]
I cannot import the project. When importing

Loading Gradle project preview failed due to an error in the referenced Gradle build. Could not fetch model of type 'GradleBuild' using Gradle distribution ihttps://services.gradle.org/distributions/gradle-3.1-bin.zip'. 
Script 'CAUsers\ hla \Documents\java-jwt\scripts\release.gradle' line: 156 
A problem occurred evaluating script. Failed to apply plugin [class 'ReleasePlugini Cannot run program "git": CreateProcess error=2, Le fichier specifie est introuvable CreateProcess error=2, Le fichier specifie est introuvable

**Comment by lbalmaceda** [comment]
@lafredi It seems that you don't have `git` binaries installed in your computer. Make sure you can run that command from the terminal.
