### ISSUE TITLE
[v2.2.0] Why use old commons-io version, will jwt work on the latest?

### ISSUE THREAD

**Issue by aquacode** [auth0/java-jwt#170]
Our project would like to use the latest commons-io library.  However, I would have to exclude jwt from pulling in version 1.3.2.  Would jwt run on a later version say 2.5?  Why is jwt using such an old version?

**Comment by lbalmaceda** [comment]
@aquacode we don't use [commons-io](https://commons.apache.org/proper/commons-io/) but [commons-codec](https://commons.apache.org/proper/commons-codec/) for `base64` and `charsets` handling. The latest version they have published is 1.10.

**Comment by aquacode** [comment]
We are using v2.2.0 of jwt and it definitely pulls in commons-io version 1.3.2

**Comment by lbalmaceda** [comment]
Right.. I thought you were using our latest. Any reason not to move to that one? If not, feel free to submit a PR with the bump and I'll review it.

**Comment by aquacode** [comment]
Should I branch off of v2 for the PR?  All I intend to do is remove the commons-io dependency from the pom.xml so the next release of v2 will not pull it in for consumers.

**Comment by lbalmaceda** [comment]
Yes, branch from `v2`. I honestly don't know if the dependency is being used at all. You'll have to check that first and if it's needed, update to the latest version and fix the issues that may appear.

**Comment by aquacode** [comment]
Done.  I am not able to push my topic branch off of v2 upstream to create the PR.

**Comment by lbalmaceda** [comment]
You should first make a **fork** of the repo, check out `v2` and branch from there to make the changes. After your done, push the branch to your fork and then come here to make a PR.

**Comment by aquacode** [comment]
Is there anything else I need to do on the PR in order for it to be reviewed and approved?

**Comment by lbalmaceda** [comment]
@aquacode it was just released as `2.3.0`. In a few hours it should be available in maven central.
