### ISSUE TITLE
I have checked out the version 3.1.0 but could not find  Algorithm algorithm = Algorithm.RSA256(publicKey, privateKey);

### ISSUE THREAD

**Issue by QuanGangDeng** [auth0/java-jwt#172]
I have checked out the version 3.1.0 ,but could not find this method in the api:
  Algorithm algorithm = Algorithm.RSA256(publicKey, privateKey);
have I made something wrong?

**Comment by lbalmaceda** [comment]
It hasn't been released yet. Meanwhile, check https://github.com/auth0/java-jwt/tree/3.1.0

**Comment by QuanGangDeng** [comment]
OK,Thanks so much,we expect to see this released version soon.

**Comment by lbalmaceda** [comment]
@QuanGangDeng This was just released and in a few hours it should be available.
