### ISSUE TITLE
When is the next release planned?

### ISSUE THREAD

**Issue by sddaniels** [auth0/java-jwt#173]
Hello! Sorry in advance if an issue isn't the appropriate place for this question:

The last release looks like it was in January. The latest changes regarding the addition of a `TokenExpirationException` look super useful. This would be great to have incorporated into a published release soon.

 Do you have a timeline for this?

**Comment by lbalmaceda** [comment]
Hi @sddaniels 
It was just released. Give it a few hours and it should be available.
Cheers.

**Comment by sddaniels** [comment]
Awesome news, thank you!
