### ISSUE TITLE
Cannot add objects as claim in token payload

### ISSUE THREAD

**Issue by sagarahire** [auth0/java-jwt#180]
Hello,

In my use case, I want to add roles object as a claim in the token payload, But there is no method in JWTCreator class which allows me to do so. Can anyone please suggest how to do this? Any help is greatly appreciated. Thank you.

**Comment by lbalmaceda** [comment]
@sagarahire Normally "roles" would be a `String` or `String[]` describing them. Those cases are supported already in the latest version. If what you need is to save a custom pojo or `Map<String, Object>`, that's not supported yet but feel free to contribute or submit your own PR like this one https://github.com/auth0/java-jwt/pull/164

**Comment by sagarahire** [comment]
Thanks @lbalmaceda
Map<String,Object> will work for me. Is there any issue with PR #164 ? Can you please tell me when this PR will get accepted?

**Comment by lbalmaceda** [comment]
@sagarahire I have reviewed it a while ago and left a [comment](https://github.com/auth0/java-jwt/pull/164#issuecomment-295764851) with the checklist the OP must fill before I merge it, but he vanished 👀 . Feel free to submit a similar PR with those conditions fulfilled and I'll merge it.

**Comment by krzyniog** [comment]
When will be available new version of java-jwt supported custom object as claim in token payload, or Map at least ? Thanks.

**Comment by lbalmaceda** [comment]
@krzyniog It's not in our current roadmap but PR's are always welcome.

**Comment by krzyniog** [comment]
@lbalmaceda thanks for the info. I have the problem with upgrade java-jwt dependency from 2.1.0 to 3.2.0. New version doesn't support passing custom object's in token payload as old version did. So, upgrade java-jwt without changing payload structure is impossible.

**Comment by lbalmaceda** [comment]
@krzyniog yes. In your case if you need custom objects in the payload you'll have to stay in the previous stable version (2.x).
