### ISSUE TITLE
Incorrect Time Format Fails Silently

### ISSUE THREAD

**Issue by zeroheavy** [auth0/java-jwt#182]
I'm developing an app and a member of my team is using this lib to ingest JWT's that I generate.  We ran into an issue that providing `exp` and `nbf` times in an inappropriate format the lib fails silently about the failure to parse.  Not sure if this intended behavior but it caused us some headaches.

**Comment by lbalmaceda** [comment]
The library follows the RFC 7519 spec, and those claims are of type `NumericDate` representing an epoch time. What is the source token you're trying to decode/verify and what is the error that you're expecting?
