### ISSUE TITLE
assertValidDateClaim should fail for null expiration/not before claim on token

### ISSUE THREAD

**Issue by zbstof** [auth0/java-jwt#184]
Currently, if the claim we explicitly asked to be verified by `JWT.require` is missing, then ... nothing happens.
I can't imagine why that should be the case.

Example:
```
DecodedJWT jwt = JWT.require(hmac512).withIssuer(username).acceptExpiresAt(0).build()
                    .verify(rawToken);
```
here, if rawToken doesn't contain `iss` claim, VerificationException is thrown, but if `exp` claim is missing, then no exception is thrown.

Fix would be to add a check for non-null date in each of 3 switch branches that deal with time in JWTVerifier.verifyClaims method.
Kinda like this:
```
case PublicClaims.EXPIRES_AT:
    checkNonNull(PublicClaims.EXPIRES_AT, jwt.getExpiresAt())
    assertValidDateClaim(jwt.getExpiresAt(), (Long) entry.getValue(), true);
    break;
case PublicClaims.ISSUED_AT:
    checkNonNull(PublicClaims.ISSUED_AT, jwt.getIssuedAt())
    assertValidDateClaim(jwt.getIssuedAt(), (Long) entry.getValue(), false);
    break;
case PublicClaims.NOT_BEFORE:
    checkNonNull(PublicClaims.NOT_BEFORE, jwt.getNotBefore())
    assertValidDateClaim(jwt.getNotBefore(), (Long) entry.getValue(), false);
    break;
```
with implementation could be:
```
void checkNonNull(String claimName, String actual) {
    if (actual == null) {
        throw new InvalidClaimException(String.format("The Claim '%s' should be present", claimName));
    }
}
```
What do you think?

**Comment by lbalmaceda** [comment]
Yes, you're right @zbstof. I think it should throw an exception if you ask to validate a date and the claim is missing.

**Comment by zbstof** [comment]
Hm, giving it another thought, it seems that `acceptExpiresAt`, `acceptNotBefore`, `acceptIssuedAt` family of functions are here only to override default leeway, but not to enforce that the claim is present.
```
private void addLeewayToDateClaims() {
            if (!claims.containsKey(PublicClaims.EXPIRES_AT)) {
                claims.put(PublicClaims.EXPIRES_AT, defaultLeeway);
            }
            if (!claims.containsKey(PublicClaims.NOT_BEFORE)) {
                claims.put(PublicClaims.NOT_BEFORE, defaultLeeway);
            }
            if (!claims.containsKey(PublicClaims.ISSUED_AT)) {
                claims.put(PublicClaims.ISSUED_AT, defaultLeeway);
            }
        }
```
Additionally, we check for claim validity only if it's present, as per original post:
```
private void assertDateIsFuture(Date date, long leeway, Date today) {
        today.setTime(today.getTime() - leeway * 1000);
        if (date != null && today.after(date)) {
            throw new TokenExpiredException(String.format("The Token has expired on %s.", date));
        }
    }
```
So we have 2 problems:
* there's no way to exclude/ignore `exp`, `nbf`, `iat` claims from the check if they are present in the request
* there's no way to enforce that  `exp`, `nbf`, `iat` claims should be present

Will it be possible to break existing clients by changing current behaviour? I can provide pull request.

**Comment by lbalmaceda** [comment]
You mentioned 2 things: 
- For the first one, I don't think ignoring a date claim would be nice. They are there to prevent the token usage and bring an extra security layer. So if the claim is present, at least compare it using the current time + the default leeway.
- For the second one, yes it's true. There's no way to enforce their presence. We can make the current `acceptXYZ` methods to have a second boolean parameter telling if the check is *optional*, meaning that in case the claim is missing don't throw an exception, but always check it if the claim is present no matter what the flag value is. These 3 **new** methods will get called from the existing ones with a "don't throw if present" value, so we don't break the current behavior.
