### ISSUE TITLE
how do we create the refresh token using this library?

### ISSUE THREAD

**Issue by pravink** [auth0/java-jwt#190]
how can we create the refresh token as well using auth0/java-jwt library?

**Comment by jspetrak** [comment]
@pravink You could post your question at Auth0 Community Forum at [https://community.auth0.com/](https://community.auth0.com).

**Comment by pravink** [comment]
@jspetrak I am using only jwt token using this library and not full oauth2. so just wondering if i can generate the refresh token as well with jwt token

**Comment by lbalmaceda** [comment]
This library is meant to create and sign as well as to decode JSON Web Tokens. If you're using Auth0, then the refresh token is issued by the server as long as you request the right scope.
