### ISSUE TITLE
Android Studio NoSuchMethodError

### ISSUE THREAD

**Issue by woliurain** [auth0/java-jwt#191]
java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
                                                                    at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:330)

**Comment by lbalmaceda** [comment]
For Android if you just need to decode a JWT then you can use [this one](https://github.com/auth0/JWTDecode.Android) as the readme says.
