### ISSUE TITLE
Improve testability by extracting an interface for JWTVerifier

### ISSUE THREAD

**Issue by mcantrell** [auth0/java-jwt#192]
For the sake of unit testing, it would be nice if there was an an interface extracted from the implementation.

**Comment by jebbench** [comment]
I have also run into the same issue; and since the class is final I can't mock it either.

**Comment by lbalmaceda** [comment]
Would it help making the class non-final?

**Comment by mcantrell** [comment]
That would solve my testing problem for sure.
