### ISSUE TITLE
The VerifyToken utility is not accurate enough with time

### ISSUE THREAD

**Issue by zippo227** [auth0/java-jwt#195]
I query a server for a token which I use to access resources on a different server. The first server is using System.IdentityModel.Tokens.Jwt to generate the token. When I run VerifyJWT on the second server, it says the the token is not valid yet, but the time it displays is the current time, down to the second. Is there a way to specify a more accurate time comparison? As of now, I'm having to subtract 1 second from current UTC time when generating the token in order to have it validated with this package.

**Comment by lbalmaceda** [comment]
@zippo227 Have you tried [this](https://github.com/auth0/java-jwt#time-validation)?

**Comment by zippo227** [comment]
Oh interesting, I didn't realize there was a leeway setting. Is there a way to just specify a more accurate comparison?

**Comment by lbalmaceda** [comment]
I don't know if I follow, but leeway is added in a single way, not both. Depending on the type of claim the way the leeway is added. i.e. it doesn't make sense to restrict an `exp` claim to an earlier date than the one defined in the token, but it does to accept a few more seconds past that token date.

**Comment by zippo227** [comment]
I see. I will test that tonight. I think it will fix my problem.
