### ISSUE TITLE
Missing JwkStore class from documented maven dependency

### ISSUE THREAD

**Issue by mab105120** [auth0/java-jwt#196]
The documentation says to use the JwkStore class to retrieve public keys from jwk store:
`final JwkStore jwkStore = new JwkStore("{JWKS_FILE_HOST}");`

The JwkStore class however is not in the package with the following dependency:

<dependency>
    <groupId>com.auth0</groupId>
    <artifactId>java-jwt</artifactId>
    <version>3.2.0</version>
</dependency>

Should I be adding any other dependencies to get it?

**Comment by lbalmaceda** [comment]
```
For simple key rotation using JWKs try the jwks-rsa-java library.
```
 
You can use that [library](https://github.com/auth0/jwks-rsa-java) or make your own implementation to obtain the set.
