### ISSUE TITLE
Why dates are divided by 1000 before token generation?

### ISSUE THREAD

**Issue by davideas** [auth0/java-jwt#201]
Sorry wrong repository... (text removed)

**Comment by lbalmaceda** [comment]
@davideas dates in JWT are expressed in "NumericDate" format, aka unix/epoch (seconds). https://tools.ietf.org/html/rfc7519#section-2.

**Comment by davideas** [comment]
So, my question was valid. Thank you, I restored the text.

But then if I want to test the dates I am obliged to remove milliseconds on my dates instances?

**Comment by lbalmaceda** [comment]
That's actually a good question. The standard just mentions that `nbf`, `iat` and `exp` claims should be of type "NumericDate" but doesn't mention anything about other date claims. In our [implementation](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/impl/PayloadSerializer.java#L46) we do convert them to/from seconds, so yes, milliseconds get stripped. To keep them, an alternative would be to set the date without using the `withClaim(String name, Date value)` method but rather a `String` or `Long` variant for the value. I don't know how breaking is changing the implementation now as the output token will differ. But if more people have the same concern I'll definitely look into it.
Cheers.
