### ISSUE TITLE
JWT token refresh

### ISSUE THREAD

**Issue by morganteg** [auth0/java-jwt#207]
Hi,

it need to know how I can perform a JWT token refreshing with auth0/java-jwt library. I already looked all java JWT object methods but I didn't found any useful method to perform token refresh.

Can anyone help me?

Thanks!

**Comment by lbalmaceda** [comment]
This library performs signing and decoding of JWT tokens, just that. What you need is an SDK that implements the authentication API, like [this one](https://github.com/auth0/auth0-java).
