### ISSUE TITLE
Support for `sub` claim

### ISSUE THREAD

**Issue by IRus** [auth0/java-jwt#21]
subj

**Comment by lordofthejars** [comment]
:+1:  it would be great to have an update to latest version.

**Comment by laguiz** [comment]
:+1:

**Comment by johnwiesel** [comment]
It would be interesting to know why this was closed?

**Comment by hzalaz** [comment]
We are cleaning old issues and gathering what improvements we need to add in the new version of the lib we are planning to build in our internal backlog.
