### ISSUE TITLE
How to import com.auth0.jwt.PemUtils.readPublicKeyFromFile

### ISSUE THREAD

**Issue by jwtLearner** [auth0/java-jwt#214]
I downloaded latest java-jwt library however it looks like com.auth0.jwt.PemUtils class is missing. How can I import this class? Thank you!

**Comment by lbalmaceda** [comment]
@jwtLearner that's a helper class for the tests. We don't provide a way to read the keys from within the library. Although, you could copy-paste that class into your app if you need it.

**Comment by kivutar** [comment]
This helper is really useful.
Why not exposing it?

**Comment by lbalmaceda** [comment]
@kivutar because how you read or obtain a key is not part of this library's scope.

**Comment by morgwaiwetrust** [comment]
@lbalmaceda could you please advise where would be the right place to add these helpers? org.bouncycastle:bcprov maybe?
Thanks!

**Comment by lbalmaceda** [comment]
@morgwaiwetrust If you ask who should own a code like this the answer is I don't know. To be honest they are simple java snippets to read PEM keys from files (no more than 3 lines each). It doesn't make any sense to create a new library just to keep them around. I've gone ahead and created a Gist to give them more visibility. 

https://gist.github.com/lbalmaceda/9a0c7890c2965826c04119dcfb1a5469

**Comment by arneke** [comment]
I have the same issue as previous commenters. Java's approach to keys (and the bc examples) is pretty daunting and it is difficult to find the right answer by searching. The gist did not make it to the front page in my searches.

Why not link to the gist from README.md , somewhere near `RSAPublicKey publicKey = //Get the key instance`

**Comment by carl-unityworks** [comment]
This is something I was looking for. One question, using a PEM file is this the same file you can download under your application's Advanced Settings/Certificate?

**Comment by lbalmaceda** [comment]
@carl-unityworks that is the public key certificate associated to the application/client tokens, correct. But it's also available publicly on the well-known endpoint. I suggest you use that one for pulling keys and verifying tokens. See https://auth0.com/docs/api-auth/tutorials/verify-access-token#how-can-i-verify-the-signature-
