### ISSUE TITLE
Why Algorithm.RSA512(..) is deprecated?

### ISSUE THREAD

**Issue by jwtLearner** [auth0/java-jwt#216]
I was following this https://github.com/auth0/java-jwt/blob/master/lib/src/test/java/com/auth0/jwt/JWTTest.java link.

I wanted to mimic following code from there.

    @Test
        public void shouldAcceptRSA512Algorithm() throws Exception {
            String token = "base64 encoded token";
            RSAKey key = (RSAKey) PemUtils.readPublicKeyFromFile(PUBLIC_KEY_FILE_RSA, "RSA");
            DecodedJWT jwt = JWT.require(Algorithm.RSA512(key)).build().verify(token) ;

            assertThat(jwt, is(notNullValue()));
    }

However from eclipse IDE, Algorimthm.RSA512(..) is deprecated. Is this right behavior?

**Comment by lbalmaceda** [comment]
We added a KeyProvider interface so you could use JWKs. What [we deprecated](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java#L129) is the method that received a single key (public or private). But you could either use the [two keys](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java#L116) alternative or the [key provider](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/algorithms/Algorithm.java#L104) one. We made these changes to have a single and reusable instance of Algorithm along your implementation.

**Comment by jwtLearner** [comment]
Understood! Thank you for your explanation and reply!
