### ISSUE TITLE
Builder : withPayload Method missing

### ISSUE THREAD

**Issue by sumanjupudi** [auth0/java-jwt#219]
Is it possible to add a builder method to add the payload claims?

e.g:
public Builder withPayload(Map<String, Object> payloadClaims)

**Comment by lbalmaceda** [comment]
This has already been discussed many times. This is not a priority for us but If want to add support for custom claims, please submit a PR and I'll be happy to review it. The conditions for us to accept it are [here](https://github.com/auth0/java-jwt/pull/164#issuecomment-295764851).
Cheers.
