### ISSUE TITLE
Payload (claims) architecture review

### ISSUE THREAD

**Issue by amanteaux** [auth0/java-jwt#22]
Hi,

The signer and the verifier are currently only working with claims as `Map<String, Object>`.
That means that if I represent a claim as a plain Java object, I have to implement methods which:
- convert my Java object to a `Map`,
- convert a `Map` to my Java object.

Since internally Jackson is used for the Json serialization/deserialization, it would be great if the signer and the verifier could work with any Java object that Jackson can serialize/deserialize.
That can be achieve if:
- `JWTSigner.encodedPayload` would take as arguments: `(Object claims, Options options)`
- Options would contains all the currently implicit parameters: iss, sub, aud, exp, nbf, iat and jti (this way the parameters would also be type-safe)
- The payload object passed to `ObjectMapper.writeValueAsString` is an object defined as `{ claims: claimsArg, options: optionsArgsValidated }`
- the method `Map JWTVerifier.verify(String token)` signature would be unchanged, but the variant `T JWTVerifier.verify(String token, Class<T> deserializeClass)` would enable to directly convert the Json object to a custom Java object.

What are your thought about that ?

**Comment by pose** [comment]
Thanks @amanteaux  We think that adding that feature will allow unnecessary complexity to the library. We might consider doing it in the future if the need arises.

**Comment by nicovanbelle** [comment]
I really miss a feature like this. I understand that from your perspective the most simple solution is the best, but I find the current feature set quite lacking.

**Comment by sarnobat** [comment]
Just a note for anyone confused - you can't "cheat" by wrapping a POJO inside n layers of java.util.Map. The validation is recursive:
```
JWTCreator$Builder.validateClaim(Map<?,?>) line: 492	
JWTCreator$Builder.isSupportedType(Object) line: 516	
JWTCreator$Builder.validateClaim(Map<?,?>) line: 491	
JWTCreator$Builder.validatePayload(Map<String,?>) line: 478	
JWTCreator$Builder.withPayload(Map<String,?>) line: 457	
JWTSigner.sign(Map<String,Object>, Options) line: 63	
```
Maybe this is obvious to others but I wasn't sure from the wording so tried it out (with v4.3.0)
