### ISSUE TITLE
Passing long value for "exp" claim with method "withClaims" throws cast exception from java.lang.Long to java.util.Date 

### ISSUE THREAD

**Issue by pshekhar07** [auth0/java-jwt#223]
I am facing an issue while generating a JWT token. When setting claim "exp" and passing a long value, I get "com.fasterxml.jackson.databind.JsonMappingException: java.lang.Long cannot be cast to java.util.Date" but when passing value, say, as "new Date(<some-long-value>)" it works, in method "withClaim". Below is my line of code:
`Long expiresWithin5Minutes = Long.valueOf(new Date(System.currentTimeMillis()+298000L).getTime());
final String jti = UUID.randomUUID().toString();
Algorithm algorithm = Algorithm.HMAC512(<jwtKey>);
final String jwtToken = JWT.create().withClaim("jti", jti).withClaim("exp", expiresWithin5Minutes).sign(algorithm);`

Also, I want to clarify on the format of "exp" claim which the library outputs. Per [ietf-doc](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#page-6), it should be in seconds from epoch. The output doesnot match the expected format.

**Comment by lbalmaceda** [comment]
`exp`, `iat` and `nbf` claims have their own setter method which expect a `Date` type. Please use that one. What it could be added from the SDK side is a validator that checks if you're setting a claim that already has a specific setter so you use that one instead (runtime exception) or an additional type check on the claim value when you're setting "numeric date" claims, so it accepts longs and dates and converts them both to seconds.

When used like above, this library outputs the correct numeric date format.
