### ISSUE TITLE
Reasonable secret length?

### ISSUE THREAD

**Issue by deviant-studio** [auth0/java-jwt#226]
Hi!
What is the best practice to generate the secret? 
Does the lib use key derivation algorithm or should we derive|generate|salt it manually with KDF function?

**Comment by lbalmaceda** [comment]
When using HS I don't know of a "best practice" for java other than using `SecureRandom` to generate the bytes. Something like:

```java
SecureRandom sr = new SecureRandom();
byte[] secret = new byte[32]; //32 bytes = 256 bits
sr.nextBytes(secret);
```

We don't do any processing to the input, we just feed it to the Mac signer along with the content to sign. Check [here](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/algorithms/CryptoHelper.java#L14).
