### ISSUE TITLE
how to make private claim as json format?

### ISSUE THREAD

**Issue by biwugang** [auth0/java-jwt#227]
how to make private claim like the following:

"access": [
        {
            "type": "repository",
            "name": "samalba/my-app",
            "actions": [
                "pull",
                "push"
            ]
        }
    ]

**Comment by lbalmaceda** [comment]
We don't support that kind of claims. JWTs should be simple and contain as little information as possible for you to interact with other services, like an Rest API, and obtain the complete data that way. Remember that these tokens are designed to be sent _on every request_ and adding such type of payload could increase the size a lot.

Related: https://github.com/auth0/java-jwt/issues/163
