### ISSUE TITLE
Framework compatibilty with Java 1.6 

### ISSUE THREAD

**Issue by hgastaud** [auth0/java-jwt#228]
Hey,

I'm working on an application that runs on a Websphere 8 and its web server runs with Java 1.6, so I faced a version mismatch error on my compilation/excecution. I've changed your code in order to compile and run with this java's version and I've succeeded. Do you guys want this code or you are not longer support this java's version?

Regards,
Hernan.

**Comment by lbalmaceda** [comment]
Hey! JDK 1.7 already reached EOL and to be honest I don't know how many people require the former. However, let's see how much of the code has changed and if that doesn't imply downgrading dependencies. Feel free to share a fork or publish a PR so we can review it.

**Comment by GrreyWang** [comment]
also run with java1.6. need support

**Comment by Radbolt** [comment]
I also am still on JDK 1.6, so Hernan's changes would be appreciated.

**Comment by lbalmaceda** [comment]
We decided not to go forward with this. Moving on the next major's minimum will probably be JDK9. If you are still looking for JDK6 support you can clone and maintain your fork.
