### ISSUE TITLE
SignatureVerificationException verifying token

### ISSUE THREAD

**Issue by zaajava** [auth0/java-jwt#229]
I joined Auth0 to evaluate using it for a new application and am trying to use this library to verify the jwt.

I have a jQuery client that makes gets a token then calls a REST  API on  the server.  I copied used the client code samples from auth0 along with the java-awt code from this site.  My API call with the generated token is successful but I always get  a SignatureVerificationException.  The code seems like it should be very straight forward.  Am I missing some basic part of the process here?

My jQuery client code:

```js
var jwtToken;
function getToken() {
	$('#jwtToken').html('');

	var settings = {
			  "async": true,
			  "crossDomain": true,
			  "url": "https://aatestauth.auth0.com/oauth/token",
			  "method": "POST",
			  "headers": {
			    "content-type": "application/json"
			  },
			  "data": "{\"client_id\":\"hwcV1O4A0y2EPM3HO819MshIS2XtSgJY\",\"client_secret\":\"{CLIENT_SECRET}\",\"audience\":\"https://localhost/ginr/rest\",\"grant_type\":\"client_credentials\"}"
			}

	$.ajax(settings).done(function (response) {
		console.log(response);
		jwtToken = response.access_token;
	});
}

function callAPI() {
  var settings = {
	"async": true,
	"crossDomain": true,
	"url": "http://localhost:8080/JwtExample/rest/simple/hi",
	"method": "GET",
	"headers": {
		"authorization": "Bearer " + jwtToken
	}
  }
  $.ajax(settings).done(function (response) {
	  console.log(response);
  });
}	  
```

My REST API:

```js
@Path("/simple")
public class SimpleAPI {

	@GET
	@Path("/{param}")
	public Response getMsg(@HeaderParam("authorization") String authorization, @PathParam("param") String msg) {

		processJwtWithSecret(authorization);;
		return Response.status(200).entity("hello").build();

	}
	
	private void processJwtWithSecret(String authorization) {
		
		String token = authorization.substring("Bearer".length());
		try {
		    Algorithm algorithm = Algorithm.HMAC256("{API_SECRET}");
		    JWTVerifier verifier = JWT.require(algorithm)
		        .withIssuer("auth0")
		        .build(); //Reusable verifier instance
		    DecodedJWT jwt = verifier.verify(token);

		} catch (UnsupportedEncodingException exception){
		    //JwkException
		    System.out.println(exception.getMessage());
		} catch (JWTVerificationException exception){
		    //Invalid signature/claims
		    System.out.println(exception.getMessage());
		}
		
	}

}
```

**Comment by lbalmaceda** [comment]
What is the exception message? It usually has more information that can help debug this. Also are you sure the API is using HS algorithm to sign the tokens and that the secret is the right one??

**Comment by zaajava** [comment]
Hi,


·         Yes, as far as I know I am using the HS algorithm to sign the tokens based on the dashboard and examples I see in auth0.  See the screen prints in the attached document.  You can see my secret value as well.

·         Regarding the exception, it fails in the HMACAlgorigth on the crypto.verifySignatureFor() method call and creates a SignatureVerificationException.


Thanks

**Comment by lbalmaceda** [comment]
You can do a self-check pasting the token you receive from the `getToken` call into https://jwt.io/:

1) the `alg` claim value in the header should be `HS256`
2) after completing the `secret` value in the page tool with your API_SECRET from the [API dashboard](https://manage.auth0.com/#/apis), you should be able to verify the token signature. Is it verified correctly? 

Please be certain of the algorithm that the resource server is set up to use as that change things a lot. You can check that accessing the [API dashboard](https://manage.auth0.com/#/apis), selecting your API and checking the value next to "Signing Algorithm". The default signing algorithm for new APIs is RS256.

![image](https://user-images.githubusercontent.com/3900123/34960782-26a4979e-fa1b-11e7-8cb8-58ec4240f367.png)

**Comment by zaajava** [comment]
I pasted the token and verified the value is HS256 but still no luck.

**Comment by lbalmaceda** [comment]
Ah I found it!
When you're extracting the token from the authorization header you're not removing the whitespace between the "Bearer" and the actual JWT.

```java
String authorization = "Bearer ey...";
String token = authorization.substring("Bearer".length());
// token = " ey..."
```

fix it by changing it to `authorization.substring("Bearer ".length());` (note the additional whitespace)

**Comment by zaajava** [comment]
Thanks, good catch.  I updated it as you showed to make sure there is no whitespace.  I still get the signature verification exception though.

I must be missing something more basic.   Don’t know if you’re free for a webex or something where I can share my desktop and walk  through it.

**Comment by lbalmaceda** [comment]
A `SignatureVerificationException` implies that either the algorithm name or the secret used doesn't match the one that the API created in [the dashboard](https://manage.auth0.com/#/apis) has, and so when attempting to verify the token signature it results in that error.

Another error I just saw is that the "issuer" you're requiring the token to have is invalid, as the tokens issued by auth0 have an issuer value of `https://{your_tenant_name}.auth0.com`. You can check that in the https://jwt.io site by decoding one of the tokens you receive. Anyway, this should throw an `InvalidClaimException` instead as seen [here](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L365). So even when this is wrong, the error happens before at the signature check step.

```java
JWTVerifier verifier = JWT.require(algorithm)
		        .withIssuer("auth0") //<-- remove this line
		        .build(); //Reusable verifier instance
```

If you say that the algorithm and secret are fine I'd double check the value you're sending in the authorization header. There's no way for me to reproduce it without you disclosing your api and client secrets and a sample token. Unfortunately we don't provide support through Github but we have other channels for you to reach us. Please try creating a ticket on https://support.auth0.com or accessing the https://community.auth0.com.

**Comment by zaajava** [comment]
Looks like the issuer value was the problem.  I had copied the code snippet below from the java-jwt<https://github.com/auth0/java-jwt> site which had “auth0”.  Now it verifies successfully using the HS256 algorithm.

Thanks again for your help!

try {
    Algorithm algorithm = Algorithm.RSA256(publicKey, privateKey);
    String token = JWT.create()
        .withIssuer("auth0")
        .sign(algorithm);
} catch (JWTCreationException exception){
    //Invalid Signing configuration / Couldn't convert Claims.
}

**Comment by lbalmaceda** [comment]
Cool! I'm glad you could solve it. I'll clarify in the readme that the snippet is a sample for future users, and will check why you received the signature exception first when the claim was wrong.
Cheers

**Comment by lbalmaceda** [comment]
I tried verifying this token which contains an issuer value of `not-auth0` as you can see [here](https://jwt.io/?value=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJub3QtYXV0aDAifQ.ume_18v1BkLGdpnmHeSV3i-ttuvQ0d7VkBg28EyRLC8)

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJub3QtYXV0aDAifQ.ume_18v1BkLGdpnmHeSV3i-ttuvQ0d7VkBg28EyRLC8
```

And then I tried to verify it with a different issuer, like you were doing before:
```java
JWTVerifier verifier = JWT.require(algorithm)
        .withIssuer("auth0")
        .build();
DecodedJWT jwt = verifier.verify(token);
```

But the exception I received was the expected one instead of the `SignatureVerificationException` that you were getting.

```
Exception in thread "main" com.auth0.jwt.exceptions.InvalidClaimException: The Claim 'iss' value doesn't match the required one.
```

Regarding the readme snippets, both the create and verify sections use the same claims as an example. I'll see how to make it clearer.

**Comment by peterchaula** [comment]
I used `token.replaceAll("(Bearer|\\s+)", "").trim()` to remove spaces anywhere in the Authorization header
