### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by Rebzie** [auth0/java-jwt#23]
There is as bit of inconsistency with the exception handling

JWTSigner.sign throws a RuntimeException and has no Exceptions in the method.
JWTVerifier.verify throws 6 types of caught exception

I think that JWTVerifier.verify  should throw GeneralSecurityException  and JWTSigner.sign should throw a checked exception

**Comment by pose** [comment]
Thanks @Rebzie, you are right. We will address that in the next major version.

**Comment by lbalmaceda** [comment]
Hi @Rebzie. 
If you can move to v3 the `verify` method now throws `JWTVerificationException` and the `sign` method throws `JWTCreationException`, both wrapping the cause inside. Check it out!

Cheers.
