### ISSUE TITLE
Getting climes without matching values then verifing

### ISSUE THREAD

**Issue by qwertukg** [auth0/java-jwt#230]
On a website https://jwt.io/ I can see my clime values, then I paste my token inside the form. But then I try to get decode my token with `java-jwt` API, all my climes has only field names, and no values. its looks like this:
```
"user_id": {
    "null": false
}
```
I know what on a website is JS library used, but i want to get my clime values too via your java API. 

Is it possible?

**Comment by qwertukg** [comment]
Then I make decode of payload part of token manually, json string is fine

**Comment by lbalmaceda** [comment]
From what you've written above I understand that the token contents are the expected ones when decoded using the jwt.io site and a JS jwt library, but using java-jwt lib they aren't. Is that correct??
In that case, I guess your token's body contains a map/dict like structure and those are not supported. We only accept plain structures (1 level).

i.e. Not supported
```json
{
  "user": {
    "name": "John",
    "address": "Street Name 123",
    "age": 90
  },
  "photo_count": 22
}
```

i.e. Supported
```json
{
  "user_name": "John",
  "user_address": "Street Name 123",
  "user_age": 90,
  "photo_count": 22
}
```

**Comment by qwertukg** [comment]
I have Climes with only one level, its plane structure, like this:
```
{
  "user_name": "John",
  "user_address": "Street Name 123",
  "user_age": 90,
  "photo_count": 22
}
```

**Comment by qwertukg** [comment]
Climes was add to Token by chaining of `withClaim` methods

**Comment by lbalmaceda** [comment]
Tokens are meant to be generated following the [rfc7519](https://tools.ietf.org/html/rfc7519) spec. It's not clear to me how you're obtaining them. Taking a sample similar to the one in the Readme, let's create and then verify a token with this library:

```java
Algorithm algorithm = Algorithm.HMAC256("secret");

//Generate a token with 3 custom claims
String token = JWT.create()
        .withClaim("user_name", "John")
        .withClaim("user_age", 52)
        .withClaim("user_married", true)
        .sign(algorithm);

System.out.println("[Token] " + token);
//prints: [Token] eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJKb2huIiwidXNlcl9tYXJyaWVkIjp0cnVlLCJ1c2VyX2FnZSI6NTJ9.R1D9UOqR7vC1RRuobBrwMheQK7S9IatrZ9Y7kUYPg7M


//Now decode it

JWTVerifier verifier = JWT.require(algorithm)
        .withClaim("user_name", "John")
        .withClaim("user_age", 52)
        .withClaim("user_married", true)
        .build(); //Reusable verifier instance

DecodedJWT jwt = verifier.verify(token);
System.out.print("[Claims] ");
System.out.print("Name: " + jwt.getClaim("user_name").asString());
System.out.print(", Age: " + jwt.getClaim("user_age").asInt());
System.out.print(", IsMarried: " + jwt.getClaim("user_married").asBoolean());
//prints: [Claims] Name: John, Age: 52, IsMarried: true
```

And if you take that token and go to [jwt.io](https://jwt.io/?value=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJKb2huIiwidXNlcl9tYXJyaWVkIjp0cnVlLCJ1c2VyX2FnZSI6NTJ9.R1D9UOqR7vC1RRuobBrwMheQK7S9IatrZ9Y7kUYPg7M) it will verify just fine and you can see the same payload claims.

![image](https://user-images.githubusercontent.com/3900123/35044640-f296dc72-fb6f-11e7-997b-40f05c0ce763.png)


Unless you provide us with a sample to reproduce the error we can't help you.

**Comment by qwertukg** [comment]
I want to get clime values without matching values then verifying

**Comment by qwertukg** [comment]
> And if you take that token and go to jwt.io it will verify just fine and you can see the same payload claims.
But jwt.io isn't pass clime values then verifying your token. That's why my question is - how to get climes **without matching values then verifying**

**Comment by lbalmaceda** [comment]
Sorry @qwertukg but I don't understand your question. Please go to http://support.auth0.com or http://community.auth0.com and continue from there. If you find an error on the library don't hesitate to open another issue.

**Comment by qwertukg** [comment]
Lets check your example:
Then you verify token, you add `withClime` methods and put values of climes there. right?
```
JWTVerifier verifier = JWT.require(algorithm)
        .withClaim("user_name", "John")
        .withClaim("user_age", 52)
        .withClaim("user_married", true)
        .build(); //Reusable verifier instance
```
If u will not chain  `withClime` methods, just `JWT.require(algorithm).build()`, climes will not be decoded. Right?

But, on a website jwt.io climes are decoded, and im sure, values (like "John", 52, true) was not pass there. Why JS library can decode it from api method (maybe), but java lib cant do this.

now I have my own extension function on DecodedJWT type who will decode payload part of token and make an object from that
```kotlin
fun <T> DecodedJWT.getPayloadData(payloadClass: Class<T>): T {
    val payloadJson = String(Base64.getDecoder().decode(payload))
    return ObjectMapper().readValue(payloadJson, payloadClass)
}
```
I can ise it like that
```kotlin
security.verifyJwt(token).getPayloadData(Payload::class.java)
```

**Comment by lbalmaceda** [comment]
The JWTVerifier is used as the name says to **verify the claims** that the given token has. Calling "withClaim" in the verifier is not mandatory, but if you do and they don't match with the ones that the token has then the verification will fail. The idea when setting up the verifier is that you will always expect a given set of values to be contained for the tokens to be accepted. For example: if you know who issued the tokens you can add that verification step by calling `withIssuer("my-server-name")` or what is the same `withClaim("iss", "my-server-name")` and that would make the verification fail if the token was not issued by "my-server-name" (meaning the token doesn't contain an "iss" claim with the expected value).

**Claims are always decoded** after you call `verifier.verify(token);`. In the `DecodedJWT` instance you get you can obtain the claim values that the token has. ALL OF THEM. Not only the ones that you have verified by using `verifierBuilder.withClaims()`.

To obtain them just call `jwt.getClaim("the-name-of-your-claim")` and that will give you a `Claim` instance to which you can call any of the methods documented [here](https://github.com/auth0/java-jwt#claim-class). If for example you want to get that claim as a custom class, you would call `claim.as(MyCustomClass.java)`.
