### ISSUE TITLE
JSON properties are not sorted

### ISSUE THREAD

**Issue by victorjss** [auth0/java-jwt#233]
In JWTCreator a Jackson Mapper is initiated in this way:

`mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);`

This does not work with Maps as is said in https://github.com/FasterXML/jackson-databind/wiki/Mapper-Features#name-handling. 

This is easily fixed removing previous line and changing the constructor of JWTCreator.Builder to use TreeMap instead of HashMap:

```
        Builder() {
            this.payloadClaims = new TreeMap<>();
            this.headerClaims = new TreeMap<>();
        }
```

**Comment by lbalmaceda** [comment]
@victorjss It's really not relevant as in JSON there's no concept of "order of the properties" (it really doesn't change things). That line was there a while ago to help us assert that the output JSON was the expected one in the tests, but we also changed the way we check JSON strings on tests to not depend on the order.
