### ISSUE TITLE
JWT package upgrade

### ISSUE THREAD

**Issue by harrisyang** [auth0/java-jwt#234]
Now we are using version 2.2, we want to upgrade to version 3.3. But I found a big change in version 3.3. What should we do? Please give us some advice? Thanks.

**Comment by lbalmaceda** [comment]
We follow [semver](https://semver.org/). That means that version 3 has breaking changes and changes most of the public API that exists on 2. If what you currently have is working then you don't need to migrate to 3. Keep in mind that we're only providing bug and security fixes to version 2.
If you still want to migrate, check the Readme as it has a few examples on the basic and advance usage.

**Comment by harrisyang** [comment]
@lbalmaceda thanks for your advice. 
We have a lot of code to use JWT based on version 2, this is not easy to migrate to version 3.
