### ISSUE TITLE
How to use auth0 with java6?

### ISSUE THREAD

**Issue by GrreyWang** [auth0/java-jwt#235]
I wanna import jwt into my project, but my project run with java6.  So, which version I can choice?  I tried version 3.0.1, but the exceptions told me can not find special class.
      By the way,  where i can find the document for every verison of jwt?

**Comment by lbalmaceda** [comment]
This is not JDK6 compatible and moving on, the next major's minimum will probably be JDK9. The file you're looking for is this one https://github.com/auth0/java-jwt/blob/master/CHANGELOG.md
