### ISSUE TITLE
`iat` should not be used for token lifetime validation

### ISSUE THREAD

**Issue by nicosabena** [auth0/java-jwt#254]
The `exp` and `nbf` claims should be used to validate the token lifetime, but the `iat` should be treated as merely informative.
The [JWT spec](https://tools.ietf.org/html/rfc7519#section-4.1.5) does not indicate any validation for `iat`. Other libraries like .Net also don't use `iat` (e.g. [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/a07d6f949dca3d26d024744d8d80c2bcfb6dd2f3/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L785)).

**Comment by wuan** [comment]
We had issues with clock skew between servers which resulted in invalid tokens in rare cases. The logic added to our verifier which now sets a default leeway if no leeway is set could be removed if `iat` is not verified to be in the past.

**Comment by DinoChiesa** [comment]
Irrespective of clock skew (which can be handled by leeway), the spec has nothing to say about whether iat ought to be considered during validation.  One may reasonably take either view: it should be considered, or it should be ignored. 

On the side of "should be ignored" - already we have  nbf and exp. These are validity times and are described as such.  Therefore using iat as well as these properties would be redundant. By this reasoning the most sensible option is to ignore iat. 

On the side of "should be considered" - common sense tells us that iat cannot be in the future. Any token with iat in the future looks bogus. 

Libraries are free to adopt either view.  java-jwt has taken the view that iat should be considered during validation. But users of libraries might differ, and it doesn't make sense to lock people into a view, given the silence in the spec on this point.  

Therefore, a simple solution: Introduce a new method on the JWTVerifier class, ignoreIssuedAt().  This calls requireClaim(ISSUED_AT, null). Then also modify the verifyClaims() method and check for null on the ISSUED_AT claim, in which case no-op.

**Comment by gedl** [comment]
Regardless of the final decision, if the `iat` check is to assert if `now` is not before `iat`, then the implementation is fundamentally wrong as it stands because it also rejects as invalid dates that are exactly `now`:

```
  case PublicClaims.ISSUED_AT:
                    assertValidDateClaim(jwt.getIssuedAt(), (Long) entry.getValue(), false);
```

which calls
```
  private void assertDateIsPast(Date date, long leeway, Date today) {
        today.setTime(today.getTime() + leeway * 1000);
        if (date != null && today.before(date)) {
            throw new InvalidClaimException(String.format("The Token can't be used before %s.", date));
        }
    }
```
Namely in tests scenario, it's not uncommon that, at second granularity, the token is verified exactly on the same timestamp, *sometimes* resulting in `InvalidClaimException`

Overall, the assertion should be if `it's not in the future` and not  ìt's in the past`

We've worked around this by issuing all tokens with 1 second leeway, but in my opinion the library should allow for exactly `equals` `iat` and `now` and not just `!now.before(date)`

**Comment by DinoChiesa** [comment]
@lbalmaceda - any update on this idea?

**Comment by lbalmaceda** [comment]
I will accept a PR with a method like the one you suggested that disables the check. But by default, it should still perform that check.

**Comment by complanboy2** [comment]
Hi @lbalmaceda, @DinoChiesa and @nicosabena 

A PR is added for this https://github.com/auth0/java-jwt/pull/297, please have a look.
