### ISSUE TITLE
Set own ObjectMapper

### ISSUE THREAD

**Issue by alabotski** [auth0/java-jwt#257]
Will be good if I can set my own ObjectMapper
```
    //Visible for testing
    ObjectMapper getObjectMapper() {
        return new ObjectMapper();
    }
```

**Comment by lbalmaceda** [comment]
I don't want to make the public API depend on a single library (jackson in this case). I guess it could be achieved if we provide our own interface to an object like that. 
This is related to https://github.com/auth0/java-jwt/issues/142. Will leave open anyway so no more issues like this one are created.
