### ISSUE TITLE
JWTVerifier and verify() are thread safe?

### ISSUE THREAD

**Issue by joolfe** [auth0/java-jwt#260]
Hi,

In an sever application like springboot API, can i create a instance of JWTVerifier and the reuse it even if more than one thread is using at same time or should i create a instance for each thread to avoid errors?

Best Regards.

**Comment by lbalmaceda** [comment]
Yes, they are meant to be reusable. You shouldn't have any thread problems. 
Closing as dupe of https://github.com/auth0/java-jwt/issues/108.
