### ISSUE TITLE
draft-cavage-http-signatures-09 support

### ISSUE THREAD

**Issue by davidkarlsen** [auth0/java-jwt#263]
also see https://issues.apache.org/jira/browse/CXF-7753
I wonder if draft-cavage-http-signatures-09 support for signing and validation is suitable to implement in this java-jwt?
I have found a couple of implementations - but they seem like single-person implementations - while java-jwt is a lot stronger community

**Comment by DinoChiesa** [comment]
It doesn't seem like support for http signatures belongs in a JWT library. Yes, they both have signatures, but they are two completely different standards.

**Comment by davidkarlsen** [comment]
OK. Closing. Thanks for responding.
