### ISSUE TITLE
Add Support for Ed25519 Elliptic Curve Key Signing of JWT Tokens

### ISSUE THREAD

**Issue by teagy-cr** [auth0/java-jwt#267]
Consider adding support for the ed25519 curve encryption key signing of JWT tokens. Verification is much faster with the same level of security.

https://ed25519.cr.yp.to

**Comment by azman6r6m1** [comment]
+1

**Comment by Quiark** [comment]
correction: with a higher level of security

but ppl should use paseto instead of jwt, it's better designed for security: https://github.com/paragonie/paseto/tree/master/docs/01-Protocol-Versions
