### ISSUE TITLE
Verify Token example using RS256 (java)

### ISSUE THREAD

**Issue by tstockton** [auth0/java-jwt#271]
The example in the README file for verifying a token uses the public and private key to validate.  In practice, the verifier will typically have only the public key.  There does not appear to be an example that shows verifying the digital signature of the token using only the public key... Am I missing something?
```
String token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJpc3MiOiJhdXRoMCJ9.AbIJTDMFc7yUa5MhvcP03nJPyCPzZtQcGEp-zWfOkEE";
RSAPublicKey publicKey = //Get the key instance
RSAPrivateKey privateKey = //Get the key instance
try {
    Algorithm algorithm = Algorithm.RSA256(publicKey, privateKey);
    JWTVerifier verifier = JWT.require(algorithm)
        .withIssuer("auth0")
        .build(); //Reusable verifier instance
    DecodedJWT jwt = verifier.verify(token);
} catch (JWTVerificationException exception){
    //Invalid signature/claims
}
```

**Comment by lbalmaceda** [comment]
Ideally, the `Algorithm` instance will be reused. 

From the top of the Readme's Usage: 

> When using RSA or ECDSA algorithms and you just need to sign JWTs you can avoid specifying a Public Key by passing a null value. The same can be done with the Private Key when you just need to verify JWTs.


You can also use a KeyProvider implementation that only returns the required keys.

**Comment by idelvall** [comment]
Came here for the same reason. Updating the example to pass a `null` in as private key would make things clearer

**Comment by lbalmaceda** [comment]
@idelvall You might have jumped right into the code, but it's there in the second paragraph https://github.com/auth0/java-jwt#pick-the-algorithm
