### ISSUE TITLE
Predicate based claim assertion

### ISSUE THREAD

**Issue by victornoel** [auth0/java-jwt#274]
In the JWT token I use, there is a claim that can contains multiple values (it's not an array, but it's not the problem here).

I'm facing a problem because I would like to be able to validate that one value is present, not that the scope completely equals a certain string.

It would thus be great if I could write:
```
JWT
            .require(Algorithm.RSA256(new JWKRSAKeyProvider(new URL(openid.jwks_uri))))
            .withAudience(clientId)
            .withIssuer(openid.issuer)
            .withClaim("scp", scps -> scps.split(" ").contains("val"))); // pseudo-code
```

So that `withClaim` could take a `Predicate<String>` (and also the other available types).

**Comment by victornoel** [comment]
(ps: I can do a PR :)

**Comment by lbalmaceda** [comment]
I'm not familiar with the `Predicate` class but I guess it's Java 8. Adding that would break existing JDK7 users. This is also not a common case. It might be for arrays but not for maps. I'll leave this suggestion open for the next major though👌 

Today, you can do the extra check right after the token signature and typical claims are verified. 

`Verify -> get claim as -> assert contains value`

**Comment by victornoel** [comment]
@lbalmaceda it doesn't have to be the actual `Predicate` class: you can introduce your own for this purpose. The important thing is for it to have only one method, so that Java 8 users can use lambdas.

Until then, I will use the method you propose :)

**Comment by rocketraman** [comment]
How about using this custom validator I just created? https://github.com/auth0/java-jwt/pull/290

**Comment by victornoel** [comment]
@rocketraman great!

That's exactly what I had in mind @lbalmaceda :)
