### ISSUE TITLE
Add some methods like withClaimObject(String,Object) or withClaimMap(String,Map) to resolve complex claims?

### ISSUE THREAD

**Issue by codingman1990** [auth0/java-jwt#304]
There are Claim.as(Class) and Claim.asMap() method,Why aren't there some methods like withClainObject(String, Object) or withClaimMap(String, Map)? Waitting for your!thx!

**Comment by iandotkelly** [comment]
It would be very helpful to be able to marshal a Map into a JSON object as a claim.  

The library won't allow us to extend this functionality in our application as the JWTCreator is final.  Would you accept a PR to add this functionality?

**Comment by josecolella** [comment]
It seems this has been asked in #135, #164, #163, and there is currently a PR https://github.com/auth0/java-jwt/pull/289 open for this. Please let us know how we can contribute to get this in library.

**Comment by mayonesa** [comment]
This is a necessity for me as the standards that I code for require claims with "context".

**Comment by navindesai** [comment]
I would really like this as well. Using it in code works, but cant add a test as we cant add a map as claim.  Not sure why this is not added.

**Comment by josecolella** [comment]
I ended up switching to jjwt (https://github.com/jwtk/jjwt), which supports using Map as claims, and it has a similar API. Made the switch very simple

**Comment by navindesai** [comment]
Thanks Jose for the information. I will have a look at this. Cheers.

**Comment by lbalmaceda** [comment]
This is present on the latest release 3.10.0
