### ISSUE TITLE
Getting json processing exception in generating jwt token

### ISSUE THREAD

**Issue by vinitjain06** [auth0/java-jwt#305]
I am getting below exception while execution

Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException
	at com.auth0.jwt.JWT.create(JWT.java:41)
	at com.mdex.controller.api.v2.Test.main(Test.java:17)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

Code is as below:

package com.mdex.controller.api.v2;
//import java.io.BufferedReader;

import java.time.ZonedDateTime;
import java.util.Date;

import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import com.auth0.jwt.exceptions.JWTCreationException; 

public class Test {
	public static void main(String[] args) {

	try {	
Algorithm algorithm = Algorithm.HMAC256("secret");
Date expirationDate = Date.from(ZonedDateTime.now().plusMinutes(60).toInstant());
String token = JWT.create()
                  .withExpiresAt(expirationDate)
                  .withClaim("username", "vinit")
                  .sign(algorithm); 
	}catch (JWTCreationException e){
		    // 
		}
	
}
}

Please help.

**Comment by Pakisan** [comment]
Looks like you forgot about dependencies.

`<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-core</artifactId>
  <version>${jackson.version}</version>
</dependency>
<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-databind</artifactId>
  <version>${jackson.version}</version>
</dependency>
<dependency>
  <groupId>com.fasterxml.jackson.core</groupId>
  <artifactId>jackson-annotations</artifactId>
  <version>${jackson.version}</version>
</dependency>`

**Comment by lbalmaceda** [comment]
@Pakisan is right though I'm not sure if we should add this dependency explicitly as part of the SDK. It is [being included as a dependency](https://github.com/FasterXML/jackson-databind/blob/master/pom.xml#L53-L57) of the `jackson-databind` package so this should not be necessary.

**Comment by vinitjain06** [comment]
Thanks.

I figured it out.

Thanks for your help.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
11/28/18,
9:44:57 AM
