### ISSUE TITLE
Support hash salt

### ISSUE THREAD

**Issue by royts** [auth0/java-jwt#31]
Hi,
This looks like a great tool, and the code it easy to read, so thanks!

I wander if there is a built in support for salt - a bunch of characters that are added to each entry in the claims object ?

If there is no option like that, what do you think about the right way to add it?
As I see it - this can be done with the existing code - I can generate the salt, add  it to each entry in the claims object and add it as an entry as well.

So instead of:

```
{ username: david1,
  lastLogin: 10-10-2015:00:00:00
}
```

I pass the following object:
```
{ username: david1xyz,
  lastLogin: 10-10-2015:00:00:00xyz,
  salt: xyz
}
```

This can be done but it feels wrong.

I think that the right way would be to use the salt when signing, and put it in the header.
This way when verifying you can user the salt again without asking from the client to save it.

What do you think?

**Comment by Rebzie** [comment]
Isn't the salt meant to be secret?

**Comment by royts** [comment]
No.
It is better but not a must. Read here:
http://en.wikipedia.org/wiki/Salt_%28cryptography%29#Benefits

being able to generate a random salt for each token is great and really make finding our the hash key harder.

If that is OK, I'll create a pull request.

**Comment by royts** [comment]
oh. wait.
Using public salt is important when saving password do DB. not relevant here.
closing.
