### ISSUE TITLE
Version 3.5.0 not visible in Maven Central repository

### ISSUE THREAD

**Issue by lewandom** [auth0/java-jwt#312]
The README states version 3.5.0 is available, but it cannot be found in Maven Central repository - http://repo.maven.apache.org/maven2/com/auth0/java-jwt/. Also latest version reported by https://search.maven.org/search?q=a:java-jwt is 3.4.1.

**Comment by lbalmaceda** [comment]
@lewandom That's true, but also weird as it seems up to date from my dashboard. I'm refreshing it now, please retry in a few hours.

```
Last Synced: Thu Jan 03 18:48:51 GMT 2019
Last Sync Status: Successfully synced without closing repo.
```

**Comment by conorwong-github** [comment]
Hi~. It can be found in http://repo.spring.io/libs-release/

**Comment by lewandom** [comment]
I can see it in Maven Central now too: https://repo.maven.apache.org/maven2/com/auth0/java-jwt/3.5.0/. Thanks @lbalmaceda.
