### ISSUE TITLE
acceptNotBefore() seems broken

### ISSUE THREAD

**Issue by tcchau** [auth0/java-jwt#314]
Context: In production, our EC2 instance, which runs our tomcat server, sometimes gets out of sync with AWS Cognito so that the JWT verification will fail. 

We are now experimenting with the acceptNotBefore() call to provide some leeway in the verification of a token and its claims. We have found, however, that using acceptNotBefore() does not seem effective.

If we create a leeway of 5 minutes by doing this:

![image](https://user-images.githubusercontent.com/3226200/51406784-16ff9080-1b28-11e9-8a61-9b08ecbe182b.png)

We will get this exception thrown:

<img width="914" alt="screen_shot_2019-01-18_at_1_28_49_pm" src="https://user-images.githubusercontent.com/3226200/51406862-54641e00-1b28-11e9-83ee-ea234cad8939.png">

This is the exact same stack trace we get in production, when the server's clock gets out of sync with AWS.

Note that we have purposely set our localhost development server to be behind the correct time by about 1 minute or so, which is reflected in the above screenshot.

However, if we instead use acceptLeeway() like so:

![image](https://user-images.githubusercontent.com/3226200/51406745-fb948580-1b27-11e9-8be5-9d3c81229ad2.png)

Then all is good, i.e. the token is verified.

Are we misunderstanding the acceptNotBefore() call?

**Comment by lbalmaceda** [comment]
The way you are using `acceptNotBefore()` is fine. Calling `acceptLeeway()` would add the leeway for the 3 date claims, same as calling the 3 methods independently.. Looking at the code, that exception message is thrown on 2 cases: https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L404-L409

If you say that by adding the `acceptLeeway` this is fixed, you might want to check that the issued_at claim of your token has the expected value. In addition to help debug this, you might want to log the current date vs the date in the given claim to narrow the issue.

**Comment by tcchau** [comment]
Thank you, @lbalmaceda ! Your troubleshooting tip helped us resolve this. Indeed, it was throwing the exception due to the second case, where the Issued At date is before the system date. I am closing this issue.
