### ISSUE TITLE
Deprecated method RSA256

### ISSUE THREAD

**Issue by bruno-vwdilab** [auth0/java-jwt#324]
Hey,

I have this code snippet:
``` kotlin
val response = service.getAccessToken(code).rawResponse
val idToken = objectMapper.readTree(response)["id_token"].asText()
val jwt = JWT.decode(idToken)
val provider = UrlJwkProvider(URL(JWK_PROVIDER))
val jwk = provider.get(jwt.keyId)

val publicKey = jwk.publicKey as? RSAPublicKey ?: throw Exception("Invalid key type")
val verifier = JWT.require(Algorithm.RSA256(publicKey)).build()

verifier.verify(idToken).token
```
The IDE warns me I'm using a deprecated method when building the RSA256 with my public key.

![image](https://user-images.githubusercontent.com/43544102/53575274-1d424d00-3b69-11e9-8b77-0efbdf8cf898.png)

I don't have access or the need to have a private key because I just want to do the verification of the token but the private key seems to be required.

There's no easy way to fix this without having the private key right? [I saw a similar issue.](https://github.com/auth0/java-jwt/issues/216) but it does not help on how to fix it.

I'm using com.auth0:java-jwt:3.7.0, com.auth0:jwks-rsa:0.7.0, JDK 10.0.1

**Comment by lbalmaceda** [comment]
@bruno-vwdilab The latest non-deprecated method is there for when you have the need to use both keys. But you can pass `null` to **one** of the parameters if you don't need to use them, as explained in the readme. 

> When using RSA or ECDSA algorithms and you just need to sign JWTs you can avoid specifying a Public Key by passing a null value. The same can be done with the Private Key when you just need to verify JWTs.


You can disregard the warning.
