### ISSUE TITLE
How to enable Proxy?

### ISSUE THREAD

**Issue by rajadilipkolli** [auth0/java-jwt#329]
We are deploying our code in openshift container and we are unable to communicate with auth0 provider as we need to connect to external world using proxy?

How to use proxy using java-jwt jar?

**Comment by lbalmaceda** [comment]
@rajadilipkolli what do you need the proxy for? This SDK doesn't make use of networking access.

**Comment by rajadilipkolli** [comment]
@lbalmaceda : We need proxy to connect to auth server and my bad the code is in jwks-rsa.jar. I should have asked question there.

**Comment by lbalmaceda** [comment]
👍 I'll proceed to close this one.
