### ISSUE TITLE
JWT verify fails on InvalidClaimException for valid before date

### ISSUE THREAD

**Issue by askorohod** [auth0/java-jwt#333]
In order to efficiently and accurately address your issue or feature request, please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. Please delete any sections or questions below that do not pertain to this request.

For general support or usage questions, please use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/).

### Description
A freshly generated token fails with "com.auth0.jwt.exceptions.InvalidClaimException: The Token can't be used before Tue May 14 06:45:59 UTC 2019."
But works a second later.
It looks like verify is checking milliseconds rather than seconds for the `iat` claim.

### Reproduction
Generate a fresh token that is valid from this second onwards (at the beginning of the second) and try to verify. Verification fails, but succeeds a second later.

**Comment by lbalmaceda** [comment]
The date claims are expressed in seconds rather than milliseconds, is normal that 1 second can cause this. Have you tried setting a leeway?
