### ISSUE TITLE
Read claims before verify

### ISSUE THREAD

**Issue by codylerum** [auth0/java-jwt#34]
Would it be possible to add the functionality to read claims from a token before we verify the token.

For example a claim may be the users id which we use to look up the secret which was used to sign the token.

Without this ability we must sign every token with the same secret.

**Comment by aj-michael** [comment]
:+1: This is pretty much necessary for the `kid` claim.

**Comment by shumy** [comment]
Yes, and should be very easy to do, ex:
```
    public Map<String, Object> payload(final String token) throws IllegalStateException {
        if (token == null || "".equals(token)) {
            throw new IllegalStateException("token not set");
        }

        final String[] pieces = token.split("\\.");
        if (pieces.length != 3) {
            throw new IllegalStateException("Wrong number of segments: " + pieces.length);
        }

        final JsonNode jwtPayload = decodeAndParse(pieces[1]);
        return mapper.treeToValue(jwtPayload, Map.class);
    }
```

Although it will get into a redundant parse with verify.

**Comment by lbalmaceda** [comment]
@codylerum @aj-michael @shumy
In v3 you can just decode the token, without any verification. 
https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWT.java#L23
Cheers
