### ISSUE TITLE
Invalidate jwt token manually

### ISSUE THREAD

**Issue by harunates** [auth0/java-jwt#341]
Hi all, 

is there any way to update expire time of jwt token?

Best Regards

**Comment by lbalmaceda** [comment]
You mean, take an existing String JWT and change its expiration? You can't change anything on the token without deeming its original signature invalid, as it's calculated from the header and payload. But I suppose you could take all the claims (header + payload), create a new one, and re-sign it. Provided you have the secret or private key and you are using a confidential client/app.
