### ISSUE TITLE
Provide a convenience method to verify a token without throwing Exception

### ISSUE THREAD

**Issue by smojum** [auth0/java-jwt#354]
### Description
Currently, we use the following code to decrypt, but as we are supporting multiple data, if we cannot decrypt, we send the original value back.

```
        try {
            DecodedJWT decodedJWT = JWT.require(algorithm)
                .build()
                .verify(sid);
            return decodedJWT.getClaim(OLD_STYLE_SID).asString();
        } catch (Exception e) {
            LOGGER.info("Could not extract the SID, assuming old-style SID is being sent, returning the same.");
            return sid;
        }
```
This works fine, but we are seeing JWTDecodeException in Dynatrace, as Dynatrace instrumentation captures this exception and reports, which is creating noise. 

The ask if a convenience method (isValid) can be provided which will check the validity of the incoming string without throwing an exception.

I can work on this issue but need to ensure that it follows design guidelines.

### Prerequisites

- [x] I have checked the documentation for this library in the README.
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/java-jwt/issues) and [PRs](https://github.com/auth0/java-jwt/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository (note this library is used by many libraries, such as [auth0-java](https://github.com/auth0/auth0-java)).

### Environment

Please provide the following:

- Version of this library used: 3.8.1
- Version of Java framework used: 1.8
- Additional libraries that might be affecting your instance: None

### Reproduction
See above for code sample

**Comment by lbalmaceda** [comment]
@smojum I don't agree this is needed, as it's just a convenience method for your particular use case. 
You can add that as a helper/utility method in your application if you plan to ignore the exception, which has valuable information BTW.

In the case of the snippet you showed above, the reasons it could fail are:
- Invalid algorithm name
- Invalid signature
- Token `exp` indicates token has expired

In any failure case listed above, the claims should **not** be used, thus why it throws and fails. Ignoring the exception and returning the string token anyway does not seem right. 

**Can you expand on why you consume the invalid token anyway?**

Regarding Dynatrace (which I'm not familiar with) I assume if the exception is catch on your java app then it shouldn't be uploaded to the service as part of the report. If this is not the case, check if there's an option to disable that and only upload un-catch exceptions, as the ones you catch are supposed to be already handled by you.

**Comment by lbalmaceda** [comment]
@smojum is this still an issue for you?

**Comment by smojum** [comment]
It is still an issue as the JWTException shows up in Dynatrace. I had a PR written for this, but i guess it did not align with the design viewpoint of the project.

**Comment by lbalmaceda** [comment]
@smojum Right. This sounds like a limitation from the Dynatrace service itself of capturing exceptions that you are already try-catch-ing. I found a reply on their community page saying you could exclude these exceptions from the logs. Check the last comment on the page.

https://answers.dynatrace.com/questions/141816/exceptions-within-a-try-catch.html
