### ISSUE TITLE
Move JWTVerifier javadoc to Verification

### ISSUE THREAD

**Issue by LeafHacker** [auth0/java-jwt#359]
### Description

When using Intellij's view javadoc feature on a `Verification` method such as `withIssuer`, no javadoc is found.

![image](https://user-images.githubusercontent.com/23565638/66859278-e51a3e00-ef82-11e9-9fc1-319ca5edb3f4.png)

### Proposed solution

Move or copy the relevant javadocs from the `JWTVerifier` class to the interface. Possibly add small javadocs on the class [linking or referring](https://stackoverflow.com/questions/10097199/javadoc-see-or-link) to the new interface javadoc.

### Reproduction

Given the following, click on `withIssuer` or `acceptLeeway` and press `Ctrl+Q`

```java
JWT.require(algorithm)
    .withIssuer(Version.API_URL)
    .acceptLeeway(120)
    .build();
```

### Environment

> Please provide the following:

- **Version of this library used:** 3.8.3
- **Version of the platform or framework used, if applicable:** Java 8
- **Other relevant versions (IDE):** Intellij IDEA Ultimate 2019.2
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by mistriel** [comment]
Definitely an issue.
Not related to any specific IDE .
