### ISSUE TITLE
Help to solve this error "javax.servlet.ServletException: com.sun.faces.renderkit.RenderKitUtils.setScriptAsRendered(Ljavax/faces/context/FacesContext;)V"

### ISSUE THREAD

**Issue by Luan-Ngoc** [auth0/java-jwt#364]
I am migrating web application that run weblogic 12.2 to Glassfish 5.0. 
When run this web application on Glassfish server, The program can get data from database and login successfully. But got exception when processing doFilter() of ServletRequest.
The following detail exception:
"javax.servlet.ServletException: com.sun.faces.renderkit.RenderKitUtils.setScriptAsRendered(Ljavax/faces/context/FacesContext;)V"

I checked RenderKitUtils class in jsf-impl-2.2.0.jar and It implement setScriptAsRendered method.
Please tell me any sulution about this exception.
Thanks

**Comment by lbalmaceda** [comment]
That exception is not pointing to any of this library's classes, I don't know how to help you. Sorry.
