### ISSUE TITLE
Claim Header - typ - Hardcoded with value JWT

### ISSUE THREAD

**Issue by pzanco** [auth0/java-jwt#369]
The Header Claim (type) should not be hardcoded with the value "JWT".  We would like to use this library to stir/shaken authentication.

https://tools.ietf.org/html/rfc8225#page-6
https://tools.ietf.org/html/rfc7515#section-4.1.9

Suggestion:

Class (JWTCreator) - Method (sign) : Verify the header claims contains the key (value = typ), if it does not exist, create one entry with value "JWT".

**Comment by lbalmaceda** [comment]
This library implements the [RFC 7519](https://tools.ietf.org/html/rfc7519) as stated on top of the readme. The `typ` of the tokens signed with this library is always going to be `"JWT"`.

**Comment by pzanco** [comment]
The library is compliant with the RFC 7519 and I enjoyed it a lot. If we have an opportunity to supply the typ value, we could use the lib to support the RFC 8225 as well.

**Comment by lbalmaceda** [comment]
Ah! sorry, I misunderstood the initial query. I don't see any short/mid-term plans to support RFC 8225. However, moving up to the constructor the `typ="JWT"` header claim value assignment can be done. In the end, is up to the dev if they want to override it. The 7519 RFC "recommends" the use of "JWT" which we will continue to provide by default.
