### ISSUE TITLE
Add support for custom Map claim

### ISSUE THREAD

**Issue by gkrizhevsky** [auth0/java-jwt#373]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

To make the library useful need to add custom Map claim when creating a new token.

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the ideal solution

The method should be like ".withMapClaim("map", map)":

String token = JWT.create()
        .withMapClaim("map", map)
        .sign(algorithm);

> A clear and concise description of what you want to happen.

Need to be able to add ad-hoc JSON map structure as claim

## Alternatives and current work-arounds

Current work-around to use JJWT or possibly hack into the JWT internals with reflection

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by kfud** [comment]
Hello, I just ran into the exact problem... +1 one from me.

**Comment by lbalmaceda** [comment]
This is present since the latest release. Check https://github.com/auth0/java-jwt/pull/282 for a hint on the usage
