### ISSUE TITLE
Improving the example for loading the public/private keys

### ISSUE THREAD

**Issue by knyttl** [auth0/java-jwt#374]
### Description

I am trying to follow the example in README.md:

```
//HMAC
Algorithm algorithmHS = Algorithm.HMAC256("secret");

//RSA
RSAPublicKey publicKey = //Get the key instance
RSAPrivateKey privateKey = //Get the key instance
Algorithm algorithmRS = Algorithm.RSA256(publicKey, privateKey);
```

However getting the key instances is not that simple. After a lot of digging I managed to load at least the private key as follows:

1. I followed https://stackoverflow.com/questions/44474516/how-to-create-public-and-private-key-with-openssl to generate public and private key.
2. I converted private key to the DER form `openssl pkcs8 -topk8 -inform PEM -outform DER -in private_key.pem -out pkcs8.der -nocrypt`
3. Now I am able to load the private key as:

```
val privateKey = readKeyAsBytes("pkcs8.der")
        .run { PKCS8EncodedKeySpec(this) }
        .run { KeyFactory.getInstance("RSA").generatePrivate(this) }
        as RSAPrivateKey
```

4. However this doesn't work for generating the public key:

```
val publicKey = readKeyAsBytes("publickey.crt")
        .run { X509EncodedKeySpec(this) }
        .run { KeyFactory.getInstance("RSA").generatePublic(this) }
        as RSAPublicKey
```

as it fails with InvalidKeyException: invalid key format. I am not sure whether .getInstnace(RSA) is correct here, but I couldn't make it work with anything else either. I guess the public key is not in the X509 format, but I cannot seem to manage to convert it to it.

It would be great to provide some better example to start with this.

### Prerequisites

(note this is not a bug)

- [x] I have checked the documentation for this library in the README.
- [x] I have checked the [Auth0 Community](https://community.auth0.com/) for related posts.
- [x] I have checked for related or duplicate [Issues](https://github.com/auth0/java-jwt/issues) and [PRs](https://github.com/auth0/java-jwt/pulls).
- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
- [x] I am reporting this to the correct repository (note this library is used by many libraries, such as [auth0-java](https://github.com/auth0/auth0-java)).

### Environment

Please provide the following:

- Version of this library used: 3.9.0
- Version of Java framework used: Java 11
- Additional libraries that might be affecting your instance: -

### Reproduction

(not a bug)

**Comment by jimmyjames** [comment]
This is related to #214. In that issue you'll find a link to a gist demonstrating how you could obtain the keys. I think updating the README to refer to that gist would help.
