### ISSUE TITLE
Disable stalebot

### ISSUE THREAD

**Issue by skjolber** [auth0/java-jwt#375]
### Description

One would think the best solution to your extremely long processing time for issues and pull-request is to divert some man-hours to reviewing pull-requests, instead of nuking by stalebot? So wrong.

### Reproduction
Add a PR, wait patiently for more than a year, see PR closed by bot ('you were too slow to react').

**Comment by jimmyjames** [comment]
Thanks for raising this. It's very valid feedback, and I agree that PRs or issues being closed due only to a maintainer's inability to respond in a timely manner is not the best way to work.

I'm taking an action item to discuss with the team the best path forward, stay tuned.

**Comment by skjolber** [comment]
Closing, since PRs seem to be getting more attention lately. Keep up the good work, pretty sure it is very cost-efficient for you.
