### ISSUE TITLE
Updating from 3.2.0 to 3.6.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [auth0/java-jwt#376]
When I try to upgrade java-jwt from 3.2.0 to the version after 3.3.0. The following code breaks.
```
public class TestJavajwt {
	
    private static final long EXPIRE_TIME = 7*12*3600*1000;
	
    public static String sign(String uid,String username, String secret) {
        try {
            Date date = new Date(System.currentTimeMillis()+EXPIRE_TIME);
            Algorithm algorithm = Algorithm.HMAC256(secret);
            
            return JWT.create()
                    .withClaim("uid", uid)
                    .withClaim("username", username)
                    .withExpiresAt(date)
                    .sign(algorithm);
        } catch (UnsupportedEncodingException e) {
            return null;
        }
    }
}
```
The code should pass, but it throws an error:
```
TestJavajwt.java:[23,11] exception java.io.UnsupportedEncodingException is never thrown in body of corresponding try statement
```

**Comment by jimmyjames** [comment]
It looks like this was introduced in #242, which was released in version 3.4.0.

You are correct that this would be a breaking change, so should have been targeted at a future major version or at the very least called out the breaking change in the `CHANGELOG.md` file. 

Unfortunately, at this point we cannot undo the change without breaking others who are not handling the `UnsupportedEncodingException`. We should update the Change log, so keeping this issue open to address that.

Apologies for the inconvenience, and thank you for raising this.
