### ISSUE TITLE
Is there a way decode the JWT without the secret?

### ISSUE THREAD

**Issue by mattblang** [auth0/java-jwt#38]
I need to be able to decode a JWT in an Android app.  I know this is possible in Angular with the JavaScript library.

**Comment by HendrikF** [comment]
JWT are encoded via Base64 only, so this should be possible.
If you mean JWE, it is impossible.

**Comment by billinghamj** [comment]
+1 there should be a way of decoding without verification

**Comment by bennythomps** [comment]
@mattblang all you should need is a Base64 decoder (many available) and break apart the three sections of the JWT, decode the middle, and you'll have your JSON payload.

**Comment by kennycason** [comment]
Any chance of doing this supporting this in the JwtVerifier? I'd like to replace my Base64 checker on my end without having to have a special class for non secret jwt verification.

**Comment by shumy** [comment]
java-jwt should definitely have a phase of Header and Payload decode before Signature verification. The issuer is useful to search for the public key.

Although there are Base64 decoders that we can use, java-jwt will already decode, avoiding a redundant decode.

**Comment by billinghamj** [comment]
@arcseldon Why have you closed this?

**Comment by hzalaz** [comment]
We are planning on writing a library specifically for Android that only decodes the token. We closed the issue since it's already in our backlog along a rewrite of this library
