### ISSUE TITLE
NullPointerException when the claim doesn't exist in the token

### ISSUE THREAD

**Issue by Raph22** [auth0/java-jwt#384]
### Description
I am not sure this behaviour is the one expected. When I try to verify a token with a claim that is not present in the token I got a NullPointerException.

### Reproduction
I got it in my own code and here's a scratch to reproduce it:

```java
import com.auth0.jwt.JWT;
import com.auth0.jwt.JWTVerifier;
import com.auth0.jwt.algorithms.Algorithm;

class Scratch {
    public static void main(String[] args) {
        String token = JWT
                .create()
                .withArrayClaim("array", new Integer[]{1, 2, 3})
                .sign(Algorithm.HMAC256("secret"));


        JWTVerifier verifier = JWT
                .require(Algorithm.HMAC256("secret"))
                .withArrayClaim("arrtay", 1, 2, 3).build(); // <== arrtay is not array

        verifier.verify(token); 
    }
}
```

### StackTrace
```
Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at com.auth0.jwt.JWTVerifier.assertValidClaim(JWTVerifier.java:412)
	at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:391)
	at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:355)
	at Scratch.main(scratch_1.java:17)
```
### Environment
- **Version of this library used: 3.4.0**

Personally I would expect to get a JWTVerificationException or InvalidClaimException.

**Comment by Raph22** [comment]
Sorry I m just realizing that there is more recent version now. I ll test tomorrow if you have changed this behaviour in the latest version and will close it if yes otherwise no.

**Comment by lbalmaceda** [comment]
Correct, it should throw an `InvalidClaimException` at least. I'll look into it. Thanks for reaching out!
