### ISSUE TITLE
Make jackson dependency optional.

### ISSUE THREAD

**Issue by kivsiak** [auth0/java-jwt#39]
Im developing android application. And in android dev we have problem with method count . The jackson lib have a huge codebase (6725 metods) against Gson which is provided. Of cause Proguard or multydex help to avoid 64k methods limit,  but but still it have strong affect on build time.

Is it possible to replace jackson with gson? In your case their functionality is almost equal.

**Comment by kirsting** [comment]
I am also developing Android application. Hope that the jackson could be optional.

**Comment by lbalmaceda** [comment]
Hi @kirsting @kivsiak,
For android we have developed a JWT decode-only capable lib: https://github.com/auth0/jwtdecode.android
