### ISSUE TITLE
Allow extraction of claims to JsonNode or ObjectNode

### ISSUE THREAD

**Issue by corby** [auth0/java-jwt#396]
I've been tooling around with the library (instead of handling JWT tokens myself).

I'd like to be able to access the claims tree directly or be able to call DecodedJWT.getClaims().toJson() that returns either a JsonNode tree or an ObjectNode tree.
I see that the claims are stored internally as JsonNodes, but is there anyway for me to access the tree as JSON objects?

Right now I have to call getClaims().toString() and use a mapper to convert them to a JsonNode object.

My current code:

```
        ObjectMapper mapper = new ObjectMapper();
        JsonNode nodeProfile = mapper.readTree(new String(Base64.getDecoder().decode(jwtProfile.getPayload())));
        JsonNode nodeToken = mapper.readTree(new String(Base64.getDecoder().decode(jwtToken.getPayload())));
```

**Comment by lbalmaceda** [comment]
No, this is not possible and I don't think we would open it as we would exposing an external dependency's API on our own. 
What about obtaining the [Map](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/interfaces/Claim.java#L96) representation of it or even a [custom class](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/interfaces/Claim.java#L106)?

**Comment by corby** [comment]
A Map representation would work fine.  It is very easy to convert a Map to what I would need.
Are we talking Map<String, T>?

**Comment by lbalmaceda** [comment]
`Map<String, Object>`. I linked to those methods above.
