### ISSUE TITLE
Does not validate not before

### ISSUE THREAD

**Issue by Rebzie** [auth0/java-jwt#40]
it looks like nbf is added as a claim to the token but JWTVerifier.verify never validates it. This is part of JWT spec and should really be verified.

**Comment by Rebzie** [comment]
created 
https://github.com/auth0/java-jwt/pull/41

**Comment by lbalmaceda** [comment]
V3 supports time validation, including `nbf` claim. https://github.com/auth0/java-jwt/blob/c07116eda79059c421794b85c148f7538421b318/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L133
