### ISSUE TITLE
NPE when trying to add null Map or List claims

### ISSUE THREAD

**Issue by Vorotyntsev** [auth0/java-jwt#416]
### Description

I'm getting a ```NullPointerException``` in ```JWTCreator#validateClaim(List<?>)``` and  ```JWTCreator#validateClaim(Map<?, ?>)``` methods when trying to add a ```null``` map or list claim.

At the same time, ```JWTCreator#addClaim(String, Object)```, that would be called after validation, accepts ```null``` values and deletes a claim in this case.

I guess, validation can be performed only on not-null maps and lists.

Please, excuse me for wasting your time if it's an expected behavior. 

### Reproduction

Code sample for List:
```
JWT.create()
    .withClaim("listClaim", (List<String>) null)
    .sign(Algorithm.HMAC256("MySecret"));
```

Code sample for Map:
```
JWT.create()
    .withClaim("mapClaim", (Map<String, ?>) null)
    .sign(Algorithm.HMAC256("MySecret"));
```

**Comment by lbalmaceda** [comment]
👋 Thanks for reaching out. I think those 2 methods should keep the behavior of the other `withClaim` methods. This is, whenever a key is non-null but the value is null, remove that key from the final claims set.
I'll move it to the backlog.

**Comment by lbalmaceda** [comment]
We should be able to release this next week. Thanks
