### ISSUE TITLE
version 3.10.3 is not in Maven Central

### ISSUE THREAD

**Issue by james-meyer-784110** [auth0/java-jwt#420]
### Description

Version 3.10.3 fails to download from Maven Central because it does not exist. Here is the [listing](https://mvnrepository.com/artifact/com.auth0/java-jwt).

### Reproduction

build.gradle

```groovy
repositories {
	mavenCentral()
}

dependencies {
...
	implementation 'com.auth0:java-jwt:3.10.3'
...
}
```

**Comment by lbalmaceda** [comment]
Thanks!
I've just synced it with central, and it will show up in the next hours. If you cannot wait, you can fetch it from JCenter.
