### ISSUE TITLE
JDK 6 support

### ISSUE THREAD

**Issue by arhmanattia** [auth0/java-jwt#424]
HEllo,

Is there a support for JDK 6 in this library

**Comment by lbalmaceda** [comment]
👋 @arhmanattia Hi. No, the min supported version for v3 is JDK 8. In the [v2 branch](https://github.com/auth0/java-jwt/tree/v2) you can find support for JDK 7, but of course, it's no longer maintained. 

We aim to support JDK versions that are still being developed or maintained.
