### ISSUE TITLE
com.auth0.jwt.exceptions.SignatureGenerationException: The Token's Signature couldn't be generated when signing using the Algorithm: SHA512withRSA

### ISSUE THREAD

**Issue by mdjava** [auth0/java-jwt#429]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

Exception in thread "main" com.auth0.jwt.exceptions.SignatureGenerationException: The Token's Signature couldn't be generated when signing using the Algorithm: SHA512withRSA
	at com.auth0.jwt.algorithms.RSAAlgorithm.sign(RSAAlgorithm.java:63)
	at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:441)
	at com.auth0.jwt.JWTCreator.access$100(JWTCreator.java:26)
	at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:419)
	at com.kalian.core.utils.JwtUtils.token(JwtUtils.java:65)
	at com.kanlian.test.eat.Test.main(Test.java:38)
Caused by: java.security.InvalidKeyException: Key is too short for this signature algorithm
	at sun.security.rsa.RSASignature.initCommon(RSASignature.java:137)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:114)
	at sun.security.rsa.RSASignature.engineInitSign(RSASignature.java:103)
	at java.security.Signature$Delegate.tryOperation(Signature.java:1286)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1234)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1332)
	at java.security.Signature.initSign(Signature.java:621)
	at com.auth0.jwt.algorithms.CryptoHelper.createSignatureFor(CryptoHelper.java:121)
	at com.auth0.jwt.algorithms.RSAAlgorithm.sign(RSAAlgorithm.java:61)
	... 5 more

**Comment by mdjava** [comment]
public static <T> String token(String audience, Date date, T claims,RSAKeyProvider provider) {
		String token = JWT.create().withExpiresAt(date) // 设置过期时间
				.withAudience(audience) // 设置接受方信息，一般时登录用户
				.withClaim(PAYLOAD, JSON.toJSONString(claims)).sign(Algorithm.RSA512(provider)); // 使用HMAC算法，111111作为密钥加密
		return token;
	}

**Comment by mdjava** [comment]
public class MyRSAKeyProvider implements RSAKeyProvider {
	static String req_pubKey = "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALMt+kBP6gISRdJuYhX6TURaMBQuPKoP" + 
			"KRh/r3549aSTiJnHDfEPnqBa9M1gS6ZwBoHD+3ywM6+OvlTJYlc/u80CAwEAAQ==";
	
	static String req_preKey ="MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAsy36QE/qAhJF0m5i" + 
			"FfpNRFowFC48qg8pGH+vfnj1pJOImccN8Q+eoFr0zWBLpnAGgcP7fLAzr46+VMli" + 
			"Vz+7zQIDAQABAkBZG3Rop1Vo0k2G6P4+j8v9QhzG7Hee2wtE87sC2oTO4vqYfzgy" + 
			"X84SnkjAoRnld3SZD5537FMMBZnRiRI530YBAiEA4xruyoFGEZriRdJ8RC7Ri2ji" + 
			"oh5+EKgcoCsVDaet1ZUCIQDJ+g4MAGBbfIOnUojVBR5WxebR1L+Pi/cJPqtg2mnP" + 
			"WQIgO6Cbp7GvavnmhPyRwfkk7Vx5fKVS5h6tfWQyX+Zxns0CIQCHwa1DX9VkaLLM" + 
			"+mrCU6hqxqY4j3kacQdgjWD/vo60MQIhALtV4JLdPeHUoTEVmVDYo78hQQQ/yfvq" + 
			"8XvV0C5CbVYA";
	@Override
	public RSAPublicKey getPublicKeyById(String keyId) {
		try {
			return RSAUtils.getPublicKey(req_pubKey);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}

	@Override
	public RSAPrivateKey getPrivateKey() {
		try {
			return RSAUtils.getPrivateKey(req_preKey);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}

	@Override
	public String getPrivateKeyId() {
		return null;
	}

}

**Comment by lbalmaceda** [comment]
There's clearly an issue reading that private key, which is being ignored because of the try/catch, and a null is being returned instead. I suggest you check your `RSAUtils.getPrivateKey` method is working OK and that the input that you're passing corresponds to a valid RS512 DER private key. Since it looks a bit short for RSA (e.g. [here]( https://github.com/auth0/java-jwt/blob/8ca949eebe0d186567be72343c6e548ade001bd6/lib/src/test/resources/rsa-private.pem )).

You can get some ideas from the `PemUtils` class and its usage https://github.com/auth0/java-jwt/blob/8ca949eebe0d186567be72343c6e548ade001bd6/lib/src/test/java/com/auth0/jwt/JWTTest.java#L436

**Comment by mdjava** [comment]
case  RSA key length is 512bits

**Comment by mdjava** [comment]
But there is another problem：
When creating a token:
withJWTId(jti)----> 022eb2e6-f471-4897-83d7-b20b30dae245
When parsing token:
JWTId(jti)--->null

**Comment by mdjava** [comment]
19:23:41.948 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withExpiresAt:<2020-07-01 19:23:44>
19:23:42.028 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withAudience:<app1>
19:23:42.028 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withIssuer:<kalian>
19:23:42.029 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withIssuedAt:<2020-07-01 19:23:42>
19:23:42.029 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withSubject:<卡联>
19:23:42.030 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withNotBefore:<2020-07-01 19:23:42>
19:23:42.030 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withHeader:<null>
19:23:42.032 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withJWTId:<022eb2e6-f471-4897-83d7-b20b30dae245>
19:23:42.033 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - withKeyId:<397fcc1b-a900-40ba-8ea7-438426224d3b>
19:23:42.343 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - data:<{"count":0,"gradeCode":"234","schCode":"123"}>
19:23:42.343 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - algorithm:<SHA512withRSA>
19:23:43.102 [main] DEBUG com.kalian.core.jwt.JwtCreateToken - token:<eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ.Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U>
19:23:43.109 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - token:<eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ.Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U>
19:23:43.236 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - no Verifier DecodedJWT:{"algorithm":"RS512","audience":["app1"],"claims":{"aud":{"null":false},"sub":{"null":false},"nbf":{"null":false},"data":{"null":false},"iss":{"null":false},"exp":{"null":false},"iat":{"null":false},"jti":{"null":false}},"expiresAt":1593602624000,"header":"eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9","id":"022eb2e6-f471-4897-83d7-b20b30dae245","issuedAt":1593602622000,"issuer":"kalian","keyId":"397fcc1b-a900-40ba-8ea7-438426224d3b","notBefore":1593602622000,"payload":"eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ","signature":"Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U","subject":"卡联","token":"eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ.Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U","type":"JWT"}
19:23:43.241 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - JWT token audiences:<[app1]>,local audience:<app1>,result flag:<true>
19:23:43.241 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - JWT token expiresAt:<2020-07-01 19:23:44> flag:<true> 
19:23:43.242 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - JWT token issuer<kalian>,local issuer<kalian>,flag:<true> 
19:23:43.242 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - JWT token notBefore:<2020-07-01 19:23:42>,flag:<true> 
19:23:43.242 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - algorithm:<SHA512withRSA>
19:23:43.263 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - Verifier after Subject(sub):卡联
19:23:43.263 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - Verifier after ContentType(cty):null
19:23:43.264 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - Verifier after Algorithm(alg):RS512
19:23:43.264 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - Verifier after Type(typ):JWT
19:23:43.265 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - Verifier after JWTId(jti):null
19:23:43.265 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - Verifier after KeyId(kid):397fcc1b-a900-40ba-8ea7-438426224d3b
19:23:43.268 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - Verifier after DecodedJWT:{"algorithm":"RS512","audience":["app1"],"claims":{"aud":{"null":false},"sub":{"null":false},"nbf":{"null":false},"data":{"null":false},"iss":{"null":false},"exp":{"null":false},"iat":{"null":false},"jti":{"null":false}},"expiresAt":1593602624000,"header":"eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9","id":"022eb2e6-f471-4897-83d7-b20b30dae245","issuedAt":1593602622000,"issuer":"kalian","keyId":"397fcc1b-a900-40ba-8ea7-438426224d3b","notBefore":1593602622000,"payload":"eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ","signature":"Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U","subject":"卡联","token":"eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ.Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U","type":"JWT"}
19:23:43.268 [main] DEBUG com.kalian.core.jwt.JwtDecodeToken - data:<{"count":0,"gradeCode":"234","schCode":"123"}>
{"count":0,"gradeCode":"234","schCode":"123"}

**Comment by lbalmaceda** [comment]
@mdjava I'm glad the original issue was solved. 
About the second one, I don't understand what's the issue. The stack trace you shared on your last comment doesn't belong to our library either. Can you explain what's wrong?

**Comment by mdjava** [comment]
That's a simple package I made

**Comment by lbalmaceda** [comment]
Let me rewrite the second issue:
- You are creating a token using this library, and setting a JWT ID of "022eb2e6-f471-4897-83d7-b20b30dae245"
- When you then try to decode that token, the JWT ID value is null?

If so, can you share the code you are calling to do that? 

The reason I ask is, I tried the token that you shared above (around the middle of the comment), I'll paste it here for reference.

```
eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ.Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U
```

You can open that same token in the [jwt.io site](https://jwt.io/?value=eyJraWQiOiIzOTdmY2MxYi1hOTAwLTQwYmEtOGVhNy00Mzg0MjYyMjRkM2IiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJhdWQiOiJhcHAxIiwic3ViIjoi5Y2h6IGUIiwibmJmIjoxNTkzNjAyNjIyLCJkYXRhIjoie1wiY291bnRcIjowLFwiZ3JhZGVDb2RlXCI6XCIyMzRcIixcInNjaENvZGVcIjpcIjEyM1wifSIsImlzcyI6ImthbGlhbiIsImV4cCI6MTU5MzYwMjYyNCwiaWF0IjoxNTkzNjAyNjIyLCJqdGkiOiIwMjJlYjJlNi1mNDcxLTQ4OTctODNkNy1iMjBiMzBkYWUyNDUifQ.Z5PsyHF9fvSM5ofvNqsZzOZQOlLvk3kC3bnBJysne0IqrgPlr6SN8JTZA0ISwCdprkvK-SLan_YlDdacVKtTvtNVVrc1KIJCCASKzCJ-7GAB8Ifx9Qd3lzIit1rVssTlXFMgDK-2rwCOfRSzXqFl7KoFdvnQCpy2ym2rJS3dH9U).


I then changed this test to use the token value above, and when I ran the tests, the output is correct 👍 
https://github.com/auth0/java-jwt/blob/master/lib/src/test/java/com/auth0/jwt/JWTDecoderTest.java#L172-L174

![image](https://user-images.githubusercontent.com/3900123/92481313-8d994800-f1bc-11ea-9bad-53a0a46a4016.png)

**Comment by jimmyjames** [comment]
@mdjava if you're still having this issue, can you share a code example as asked above? Otherwise we'll consider this issue closed per the findings above. Thanks!

**Comment by jimmyjames** [comment]
Closing this issue as we haven't heard back; if you'd like it reopened please comment and provide a code sample of the issue so we can investigate further. Thanks!

**Comment by royal0527** [comment]
com.auth0.jwt.exceptions.SignatureVerificationException: The Token's Signature resulted invalid when verified using the Algorithm: SHA256withRSA

please help me this
the code is,

boolean isvalid = false;
			// For Azure AD V2 token
			String providerURLV2 = "https://login.microsoftonline.com/" + "38253190-d7a0-40fa-b9f2-9116d26f0560" + "/discovery/keys?appid=d6e3f014-a207-409f-b2cf-4ea8abe0d3ef";
			String issuerV2 = "https://login.microsoftonline.com/" + "38253190-d7a0-40fa-b9f2-9116d26f0560";
			try {
				log.info("inside jwt token verification");
				DecodedJWT decodedJWT = JWT.decode(token);
				log.info("decoded jwt"+decodedJWT);
				JwkProvider provider = new JwkProviderBuilder(new URL(providerURLV2)).build();
				log.info("provider jwt"+provider);
				Jwk jwk = provider.get(decodedJWT.getKeyId());
				log.info("jwk jwt"+jwk);
				Algorithm algorithm = Algorithm.RSA256((RSAPublicKey) jwk.getPublicKey(), null);
				log.info("algorithm algorithm"+algorithm);
				JWTVerifier verifier = JWT.require(algorithm).withIssuer(issuerV2).build();
				log.info("verifier verifier"+verifier+"exit");
				System.out.println(verifier.verify(decodedJWT).getClaims());
				return isvalid = true;
			} catch (Exception e) {
				e.printStackTrace();
				return isvalid = false;
			}
