### ISSUE TITLE
Add factory method to create an Algorithm from a java.security.Key

### ISSUE THREAD

**Issue by fvasco** [auth0/java-jwt#434]
We wish to verify a JWT using a Java's Key.
Unfortunately, we cannot found a simple way to create an `Algorithm` starting from a `Key`.

Currently our code looks like:

```kotlin
    val algorithm = when (jwtKey.algorithm) {
        "HmacSha256" -> Algorithm.HMAC256(jwtKey.encoded)
        "HmacSha384" -> Algorithm.HMAC384(jwtKey.encoded)
        "HmacSha512" -> Algorithm.HMAC512(jwtKey.encoded)
        // and so on...
        else -> error("Unsupported algorithm ${jwtKey.algorithm}")
    }
```

We think that this mapping should be delegated to library, ie:

```kotlin
    val algorithm = Algorithm.forKey(jwtKey)
```

Please keep in mind #252

**Comment by lbalmaceda** [comment]
Once this library was explicitly supporting RSAKey / RSAPublicKey and then went a bit up and used PublicKey and PrivateKey. Going one level of abstraction further to Key does not sound correct. Here, the more explicit the developer is when setting up sensitive things such as the expected algorithm and keys, the better. @jimmyjames thoughts?

Regarding #252, I don't see the reason to go back to single key constructors. If you're not signing tokens then pass null for the private key. Both fields are nullable, as long as when the Algorithm begins to sign/verify can find one of them.

**Comment by fvasco** [comment]
> the more explicit the developer is when setting up sensitive things such as the expected algorithm and keys

In my use case, the algorithm is a parameter, not a developer choice.
WE need a way to verify a JWT without have to maintain the above mapping, in other words, a generic way to build an `Algorithm`, something like `Algorithm.build(algorithm, publicKey, privateKey)` (including `publicKey == privateKey` for simmetric algorithm)

**Comment by lbalmaceda** [comment]
I don't think this library will add support for more algorithms, honestly. We received only one PR in more than 2 years and is still waiting on the contributor to come back. The maintenance of this mapping that you're doing in your app is low today. Anyway, I understand where you want to get and while this is not in our scope, we are happy to help you contribute to this change by reviewing the code you or anyone else submits.

Without digging deeper into the library, how I see this "algorithm factory", is not going to be exactly 100% generic with a single method. But maybe it can be resolved with 2 different signatures. The acceptance criteria I can think of now: 
1. It will need to handle both asymmetric and symmetric "keys", for generating HS algorithms and RS/ES algorithms. The asymmetric "key" is always a secret string or a byte array.
2. It will only provide support for [our currently supported algorithms](https://github.com/auth0/java-jwt#available-algorithms), detailing in the docs that this is the case.
3. It will need to understand when an asymmetric key is public and when private.

If you're happy with that or want to keep discussing the implementation, drop a comment below 👍

**Comment by lbalmaceda** [comment]
@fvasco I've discussed this change with the team and decided is not something we want to include to the library today. In a typical backend or web application, the algorithm used will be only one, and its name and value should be explicitly decided by the developer and not let out for a dynamic resolution. This will ensure the signature generation/verification process is less error-prone as well.

I'll close this now.
