### ISSUE TITLE
The exception try(){}catch{} suggession

### ISSUE THREAD

**Issue by ballchencz** [auth0/java-jwt#436]
**When I removed several bits of a signed token**,My system throws an "IllegalArgumentException", but I hope it throws "JWTDecodeException", When I checked the source code, I found that the "JWTDecoder" constructor only caught a null pointer exception and threw "JWTDecoderException". Therefore, I hope to catch the runtime exception here, so that I can handle the token parsing failure in the exception handling instance of my system

**Comment by jimmyjames** [comment]
Hi @ballchencz,

We do have a fix for this issue that has been merged, but not yet released. We're planning to do the release this week.

[Here is the change](https://github.com/auth0/java-jwt/pull/426), if you'd like to try it out and verify that it addresses the issue, that would be great. Thanks!

**Comment by lbalmaceda** [comment]
Fixed in 3.11.0
