### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Gagandeep1408** [auth0/java-jwt#437]
java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)

*************Code***************
 val header: MutableMap<String, Any> = HashMap()
        header["alg"] = "HS256"
        header["typ"] = "JWT"

    
        try {

                val algorithm: Algorithm = Algorithm.HMAC256("***************************")
                val token: String = JWT.create().withHeader(header)
                    .withClaim("merchantId", "20070001001256")
                    .withClaim("loginid", "********************")
                    .withClaim("password", "********")
                    .withClaim("language", "en")
                    .sign(algorithm)

            showLog("valuesss", ">>>>>" + token)

        } catch (exception: JWTCreationException) {
            //Invalid Signing configuration / Couldn't convert Claims.
        }

**Comment by lbalmaceda** [comment]
@Gagandeep1408 where are you running this?

**Comment by Gagandeep1408** [comment]
I'm implemented in android and when i try to run app in Android version
8.1. App crashed.

**Comment by lbalmaceda** [comment]
The readme states that this library is not for Android. And signing tokens in a public client such as native app doesn't make much sense, since you can't keep the secret confidential.
