### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by Gagandeep1408** [auth0/java-jwt#441]
java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)

**Comment by lbalmaceda** [comment]
@Gagandeep1408 on what application or platform are you using this?

**Comment by Gagandeep1408** [comment]
Android , On my some devices its working fine

**Comment by lbalmaceda** [comment]
@Gagandeep1408 the android platform is not supported (see the top of the README). Please take a look at all the [related closed issues](https://github.com/auth0/java-jwt/issues?q=is%3Aissue+android+is%3Aclosed) before opening a new one next time.
