### ISSUE TITLE
Suggestion to create method withPayload in JWTCreator.java

### ISSUE THREAD

**Issue by onmax** [auth0/java-jwt#445]
### Description
Rigth now, I have my own implementation of a JWT with its own Header and Payload class. But, I am struggling with signing, decoding and verifying the JWT so I have decided to use an external library like this one. As I said, I already have my own payload (and it is kind of extensive), it has a lot of keys and values. Some of them are JSONObjects so if I want to use this library I just can't initialize JWTCreator because I don't have the function withClaim(String name, Object value) in [this file](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTCreator.java). 

So, it is a reason for this? I suggest create a new method similar to withHeader but for the payload. 

Maybe there is another solution that I don't know so this change is unnecessary.

If you think this is a good idea, I am up to make the change and create the tests

**Comment by onmax** [comment]
Hey, any comment on this?

**Comment by JordiGiros** [comment]
I'm struggling with the same problem. I read my own Payload from a json file and I have a lot of keys and values. I was looking for an approach with a map, but there is no way to pass a map to the claims without setting a "name" to that...

**Comment by jimmyjames** [comment]
Thanks for the request, I think this makes sense to add.

We've added this to our backlog, to add a method `withPayload` that accepts of a map of claim names -> values. In the meantime, would be happy to review or discuss specifics if someone is interested in making a PR. We'll need to ensure that we're consistent with how we validate the claims (non-null claim name, valid object types for serialization purposes, etc), and verify/document behavior if calling this new method and the other `withClaim` methods. 

/cc @lbalmaceda
