### ISSUE TITLE
How to conditionally build com.auth0.jwt.algorithms.Algorithm instance based on properties

### ISSUE THREAD

**Issue by kamath237** [auth0/java-jwt#446]
I have this JWT validation block where I need to build an Algorithm instance based on the 'alg' used by Identity Provider for signing. It could be 'RS256', 'HS256', 'RS512' or anything else.

```
Algorithm algorithm = Algorithm.RSA256((RSAPublicKey) getPublicKey(), null);
Verification verifier = JWT.require(algorithm);
verifier.build().verify(Jwt);
       
```
So my line of code "Algorithm.RSA256((RSAPublicKey).... " is now kind of hardcoded. How do I make this generic based on an Environment property input?
I'm using below version.

		<dependency>
			<groupId>com.auth0</groupId>
			<artifactId>java-jwt</artifactId>
			<version>3.10.3</version>
		</dependency>

**Comment by lbalmaceda** [comment]
@kamath237 The constructor for the Algorithm class has _protected_ visibility, so this wouldn't be possible today. I assume you could do a when/switch statement over the algorithm name variable to decide that. Can you share a bit more about your use case? Especially about how that algorithm name value is dynamic and not known in advance.

Related: https://github.com/auth0/java-jwt/issues/434

**Comment by kamath237** [comment]
@lbalmaceda I intend to do this in my product which goes to different customers who would invoke the APIs 
that this product exposes with their own auth server issued token. As per the customers token specifications, I just need to update my application.yml with alg, issuer, x5c etc required to verify JWT - No choose changes and rebuild.

As you mentioned, switch case is an option, but I need to bring up an exhaustive list.

**Comment by lbalmaceda** [comment]
We don't have plans to add support for more algorithms in the near future, and we also don't want to support instantiating algorithms from a string / name value (decision made on the issue linked above). HS vs RS/EC algorithms vary in how the "secret" piece is passed, so there's no nice generic solution that we can ship with the SDK. 

Although you might want to limit the allowed algorithms that your API supports, depending on your specific use case; you will have to maintain this list or switch yourself in case this happens to change.

**Comment by lbalmaceda** [comment]
Closing this issue as our decision is final.
