### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [auth0/java-jwt#451]
The README file in this repo has some bad links - [404:NotFound]

Status code [404:NotFound] - Link: https://docs.auth0.com/identityproviders
Status code [404:NotFound] - Link: https://docs.auth0.com/mysql-connection-tutorial
Status code [404:NotFound] - Link: https://docs.auth0.com/link-accounts
Status code [404:NotFound] - Link: https://docs.auth0.com/jwt
Status code [404:NotFound] - Link: https://docs.auth0.com/rules

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by lbalmaceda** [comment]
@MrCull Thanks for reporting this. It has now been fixed.
