### ISSUE TITLE
Required Java version is changing to 8

### ISSUE THREAD

**Issue by lbalmaceda** [auth0/java-jwt#457]
## Description

Java 7 (2011) stopped receiving public updates on 2015, only Oracle extends its support nowadays. Due to most libraries moving to and requiring Java 8 during the past years (see references), we are now making the decision of updating this SDK’s minimum required Java to the version 8 in a _minor_ package release.

This will enable us to pull the changes for the next planned major version sooner into the current branch and without introducing additional breaking changes.

**A new minor version will soon be published that will target Java 8. At that time, Java 7 will no longer be supported.**

We plan to make this release no sooner than 30 days from this posting. If our timeline needs to be adjusted for any reason, we will follow-up here.

## Resources

- https://www.oracle.com/java/technologies/java-se-support-roadmap.html
- https://developer.squareup.com/blog/okhttp-3-13-requires-android-5/
- https://commons.apache.org/proper/commons-lang/release-notes/RELEASE-NOTES-3.9.txt

**Comment by downdrown** [comment]
Will you update the implementation to use `java.time.*` classes instead of `java.util.Date` too?

**Comment by jimmyjames** [comment]
@downdrown we will be able to do that, though not directly as part of this issue. We should be able to pull #403 and #392 forward to master now. It's not something I'll have bandwidth for before the end of the year, but if anyone's interested and would like to make a PR, would be happy to take a look after the holidays (please create an issue first if you don't mind).

**Comment by jimmyjames** [comment]
Issue fixed with #455, released in version `3.12.0`.
