### ISSUE TITLE
A minor error in README.md, apparently

### ISSUE THREAD

**Issue by troy-civitas** [auth0/java-jwt#46]
The example given is slightly off:
```
            Base64 decoder = new Base64(true);
            byte[] secret = decoder.decodeBase64(CLIENT_SECRET);
```
decodeBase64() is a static function, but it's being called in the context of a java instance variable - this might be legal (i've been copying and altering for scala myself) but it doesn't really make sense, so I would suggest 
```
            //Base64 decoder = new Base64(true);
            byte[] secret = Base64.decodeBase64(CLIENT_SECRET);
```
or 
```
            byte[] secret = decoder.decode(CLIENT_SECRET);
```

**Comment by arcseldon** [comment]
Readme updated.
