### ISSUE TITLE
Verifier error for verifying claims

### ISSUE THREAD

**Issue by BaljitKarwal** [auth0/java-jwt#460]
I am using this library and used a very basic function to create the token which worked as expected and when I am trying to verify the same token, the verifier throws this error: "java.lang.ClassCastException: java.lang.String incompatible with java.util.List"

Below is my createToken function:
`validToken = JWT.create()
	    				.withIssuer(apiKey)
				    	.withClaim("iss", apiKey)
			            .sign(algorithm);`

And below is the verifyToken fucntion:
` JWTVerifier verifier = JWT.require(algorithm)
				    		.withIssuer(apiKey)
					    	.withClaim("iss", apiKey)
					        .build();
				    DecodedJWT jwt = verifier.verify(validToken);`

Below is the printStackTrace:
HTTP JVM: CLASS: Authorizer *** java.lang.String incompatible with java.util.List
HTTP JVM: java.lang.ClassCastException: java.lang.String incompatible with java.util.List
HTTP JVM:  at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:304)
HTTP JVM:  at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:278)
HTTP JVM:  at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:261)

**Comment by jimmyjames** [comment]
Hi @BaljitKarwal,

Any reason you are adding the issuer twice, once with `withIssuer` and once using `withClaim`? If you are calling `withIssuer`, there is no need to also call `withClaim`. That should fix the problem.

**Comment by BaljitKarwal** [comment]
Thanks @jimmyjames .That worked. Remove issuer from the claim.
