### ISSUE TITLE
Use java.util.Base64

### ISSUE THREAD

**Issue by jimmyjames** [auth0/java-jwt#461]
Use java.util.Base64 for encoding and decoding, instead of the apache lib. Depends on #457.

**Comment by XakepSDK** [comment]
Help needed?

**Comment by jimmyjames** [comment]
@XakepSDK yes that would be great! One thing I'm not so sure about is if this truly can be done in a way that doesn't involve a breaking change in behavior. We should be able to find out with our existing tests, but we need to be careful that we don't introduce a breaking change in v3.

**Comment by jimmyjames** [comment]
Closed with #478, thanks @XakepSDK! Will include in a new release later this week or next week.

**Comment by gkrat** [comment]
Do you know when this might be released?

**Comment by jimmyjames** [comment]
3.15.0 uses java.util.Base64 instead of commons-codec.
