### ISSUE TITLE
Claim implementation does not match Claim Interface documentation

### ISSUE THREAD

**Issue by dude-abides** [auth0/java-jwt#466]
Issue:
I am trying to iterate over claims and print them for debugging purposes. So I call asString() on every claim. It seem Boolean claims always return null. 

https://github.com/auth0/java-jwt/blob/6b802545d97d40208ea0c3945f5300da904fcf45/lib/src/main/java/com/auth0/jwt/impl/JsonNodeClaim.java#L54

Comments:
1. I don't see a way to determine the type of a claim. It would be nice to have a getClaimClass() or getClaimType()
2. The interface docs. for asString in Claim suggests that if a type can be converted to String, then that would be returned.
3. It appears the toString() is the default impl. it might be nice to have this be: return value == null ? null : value.toString()

**Comment by lbalmaceda** [comment]
1. The types one could find are either string, number, or boolean. Although a claim can also have a null value. You either get claims listed in the [7519 specification](https://tools.ietf.org/html/rfc7519) or make use of custom claims that you've added yourself (or a service you own or documents its claims) and can anticipate their type. There's no generic solution for iterating over them and telling the type.

2. I agree the "can be converted to" is not applying to the implementation, but in reality, it talks about how Jackson can deserialize a `JsonNode` into a given type.

3. Yes, `claim.toString()` could return what `data.toString()` returns. I'm tracking this internally as SDK-2225.
