### ISSUE TITLE
The Token can't be used before xxxxx

### ISSUE THREAD

**Issue by saiyujs** [auth0/java-jwt#467]
hi

this is the token : eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJpc3N1ZXIiLCJleHAiOjE2MDkxNDA3MTQsImlhdCI6MTYwOTEzNzExNCwidXNlcm5hbWUiOiJhZG1pbiJ9.UBaAyr3AC0FDaiYY5dtgN_TbYin0s37iILSua9AELkU

error: com.auth0.jwt.exceptions.InvalidClaimException: The Token can't be used before Mon Dec 28 14:31:54 CST 2020.

token debug: {
  "iss": "issuer",
  "exp": 1609140714,
  "iat": 1609137114,
  "username": "admin"
}

expire time is 2020-12-28 15:31:54, why it say token can't be used before Mon Dec 28 14:31:54 CST 2020 ??? it looks use the iat?

version: <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>3.10.3</version>
        </dependency>

**Comment by lbalmaceda** [comment]
Yes, the "issue at" (iat) claim is checked when you verify a token. See https://github.com/auth0/java-jwt#time-validation. If you need to disable that specific check, you can do so using the following [method](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L108).

**Comment by amjadali-dev** [comment]
You can also use the inbuild method ignoreIssuedAT().
Java example
JWTVerifier jwtVerifier = JWT.require(algorithm).ignoreIssuedAt().build();

**Comment by vergenzt** [comment]
FYI I've submitted an errata request to [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519) to update the spec to explicitly prohibit rejecting tokens with `iat` from "the future".

Feel free to follow along here: [Discussion: JWT tokens containing `iat` values in the future should not be rejected](https://gist.github.com/vergenzt/05aa83a48fcac46cd5b5c8696a9b186a)
