### ISSUE TITLE
Update documentation for acceptIssuedAt 

### ISSUE THREAD

**Issue by guo-hong** [auth0/java-jwt#470]
### Describe the problem you'd like to have solved

"IssuedAt" (IAT) claim verification has been made optional following the close of [issue-254](https://github.com/auth0/java-jwt/issues/254). However ["acceptIssuedAt"](https://github.com/guo-hong/java-jwt/blob/5a65f3007dff73079534602ce58d26c09fedac8b/lib/src/main/java/com/auth0/jwt/interfaces/Verification.java#L73) documentation is not updated and confusing. 

### Describe the ideal solution

If the documentation of "acceptIssuedAt" function can be updated to state that IAT claim verification is by default but optional, it will make it clear and avoid confusion. I can provide a PR to update it.

**Comment by jimmyjames** [comment]
Thanks for raising @guo-hong.

I've made #471 to address, would appreciate your review to see if that change addresses the confusion. Thanks!

**Comment by guo-hong** [comment]
Thanks @jimmyjames . The PR looks great.
