### ISSUE TITLE
Add one-of functionality to verification of list claims

### ISSUE THREAD

**Issue by jorundoa** [auth0/java-jwt#474]
### Add one-of functionality to verification of list claims

Currently the verification of a claim implemented as a list using `withArrayClaim()` verifies the claim object using a `containsAll()`-function. Meaning the token must include _all_ of the elements present in the list input to `withArrayClaim()`.

##### Problem:
A "one-of" check when verifying a list claim is valid. (See for example: https://github.com/auth0/java-jwt/pull/472 and the verification of Issuer.  They both use the "one-of" verification. ) However it is now limited to only the hardcoded issuer and audience. 

##### Use-case:
My company uses company-roles as a a claim in the token. ("roles: ["admin", "team-member"]). The roles I would like to verify a token with could be mutually exclusive, meaning a user only has one of them. For example: "grant access if user has _either_ "admin" or "consultant" role. 

### Solution: Add "anyOf" methods in addition to the `withArrayClaim()`-methods.

Extend the interface to also include `withAnyOfArrayClaim()` similar to the `withAnyOfAudience()` that will verify if the claim in the token contains _any_ of the elements in the given list. 

## Current workaround:

Currently we remove the `withArrayClaim()` from the JWTVerifier usage and rather validate the claim manually from the DecodedJWT. This has created some structural issues in the code and feels unsafe going outside the library for such an important validation step. 

### Additional context

This PR: https://github.com/auth0/java-jwt/pull/472 essentially makes the changes, but _only_ for audience. However audience is not the only valid "one-of" claim. 

I realise `withArrayClaim()` is to be deprecated in the next version: https://github.com/auth0/java-jwt/pull/403
This functionality will not easily be implemented with the map-based objects, as you'd have to specify each map-level as either a "one-of" or a "exact-match". 

I've seen multiple attempts at "custom" or "map base" validation functionality being denied. In my eyes this is not added functionality so much as it should have been available from the get-go when withArrayClaim was added.

**Comment by jimmyjames** [comment]
Thanks for the detailed information and use case. This does seem like a valid use case to support. We'll add it to our backlog; it may not be something we tackle immediately, but will be good to support.

**Comment by jorundoa** [comment]
Thanks! Is there anything I can do to help speed up the process? At the moment we are using the workaround, but I'd prefer it if we could avoid it as soon as possible, :)

**Comment by jimmyjames** [comment]
@jorundoa thanks for your engagement!

My only concern with adding this to v3 is the need to add more default methods to the `Verification` interface, that would need to throw an `UnsupportedOperationException`. While I don't expect that many customers are implementing that interface directly, especially in non-test scenarios, it does start to feel... non-ideal.

I'm not sure there's a great alternative to that without waiting to a v4, for which we can't provide an ETA at this time. I'd love feedback on the proposal of adding `withAnyOfArrayClaim` methods to the `Verification` interface that would throw an exception by default, and if anyone is implementing/extending that interface in their usage. If it is low-impact, I'm happy to make or review a PR to support this.

**Comment by kkolodzi** [comment]
śr., 10 lut 2021, 09:04 użytkownik Jørund Amsen ***@***.***>
napisał:
