### ISSUE TITLE
Version 3.14.0 not on Maven Central

### ISSUE THREAD

**Issue by kebeda** [auth0/java-jwt#480]
### Describe the problem you'd like to have solved

Version 3.14.0 fails to download from Maven Central because it does not exist. All maven jobs using this version fail.

**Comment by jimmyjames** [comment]
Hi @kebeda - I just resynced from jcenter to maven for 3.14.0. It may take a bit (sometimes a few hours) to show up in maven central. I'll check back in tomorrow to make sure it's there.  In the meantime you can use jcenter if you. need 3.14.0 right. now. Thanks!

**Comment by kebeda** [comment]
Yes, this is on Maven Central now thanks! I'd love to use jcenter, but am unable to, so thanks for doing this.
