### ISSUE TITLE
Remove jcenter

### ISSUE THREAD

**Issue by XakepSDK** [auth0/java-jwt#481]
### Describe the problem you'd like to have solved
JCenter is closed
https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

### Describe the ideal solution
Remove jcenter from build scripts

### Alternatives and current work-arounds
None

### Additional information, if any
None

**Comment by jimmyjames** [comment]
Thanks @XakepSDK - #482 submitted to remove jcenter from our repo dependencies.
