### ISSUE TITLE
Add module system support

### ISSUE THREAD

**Issue by XakepSDK** [auth0/java-jwt#483]
### Describe the problem you'd like to have solved
I'm writing desktop application and i want module system support for this library, so i can have smaller runtime

### Describe the ideal solution
Since Java 8 is the minimum java version, we could:
1. Compile everything with Java 11 compiler with `--release 8`, so we will have Java 8 version classes
2. Add module-info file compiled with `--release 9`
Classes with dash are ignored by VM, so Java 8 VM will be able to load jar with `module-info.class`

## Alternatives and current work-arounds
Use automatic module name, it won't give any benefit of module system, we will just claim module name

### Additional information, if any
Module name components can't end with digits and this library package is `com.auth0.jwt`, not sure how to deal with that `0`, compiler warns about it

**Comment by XakepSDK** [comment]
Not stale

**Comment by lbalmaceda** [comment]
Closed with the PR linked above. Will be available soon.
