### ISSUE TITLE
Duplicate GitHub issue template for bugs

### ISSUE THREAD

**Issue by Marcono1234** [auth0/java-jwt#486]
It appears there are currently two GitHub issue templates for bugs:
- [`report-a-bug.md`](https://github.com/auth0/java-jwt/blob/master/.github/ISSUE_TEMPLATE/report-a-bug.md)
- [`report_a_bug.md`](https://github.com/auth0/java-jwt/blob/master/.github/ISSUE_TEMPLATE/report_a_bug.md)

Both specify the same name, so GitHub currently shows neither of them:
![GitHub issue type selection screenshot](https://user-images.githubusercontent.com/11685886/113062536-2ffa3680-91b4-11eb-8e02-a32ffbb3f1d3.png)

**Comment by lbalmaceda** [comment]
Thanks for pointing this out. I just created a PR for it.
