### ISSUE TITLE
Hide `impl` package from javadoc (and module declaration)

### ISSUE THREAD

**Issue by Marcono1234** [auth0/java-jwt#487]
### Describe the problem you'd like to have solved
It appears the `impl` package contains part of the internal implementation and should not be used by the user.
However, some of its classes are public and there is no indication to the user that they should not be used.

### Describe the ideal solution
- Hide the package from javadoc
- Add a `package-info.java` file documenting that the package is part of the internal implementation and classes inside of it should not be used.
- Don't export the package from the module declaration, see also #483. (Ideally in the next major version since it is a breaking change)
- Remove mentions of `impl` classes from API documentation:
  - `NullClaim`: Mentioned from
    - `Header.getHeaderClaim`
    - `Payload.getClaim`

**Comment by lbalmaceda** [comment]
> Hide the package from javadoc

This would be solved with the changes you proposed for #489.

> Add a `package-info.java` file documenting that the package is part of the internal implementation and classes inside of it should not be used.

If the package is no longer going to be included in the javadocs, we can probably skip this change if the intent is just to hide the `impl` package.

> Remove mentions of `impl` classes from API documentation:

Good catch! These should also be removed. If you want to take them as well with the same PR that's OK to us.

**Comment by Marcono1234** [comment]
> > Add a `package-info.java` file documenting that the package is part of the internal implementation and classes inside of it should not be used.
> 
> If the package is no longer going to be included in the javadocs, we can probably skip this change if the intent is just to hide the `impl` package.

Maybe it would be useful nonetheless so it is obvious to users browsing the code that the package contains internal implementation details.

**Comment by jimmyjames** [comment]
> Maybe it would be useful nonetheless so it is obvious to users browsing the code that the package contains internal implementation details.

I agree; it's worth adding.

**Comment by jimmyjames** [comment]
Fixed with https://github.com/auth0/java-jwt/pull/496, shipped in 3.16.0
