### ISSUE TITLE
TokenUtils:: splitToken need to optimize on split()

### ISSUE THREAD

**Issue by pravsingh** [auth0/java-jwt#506]
### Describe the problem

Use of String.split() with regex param is not optimal. Given the library is used heavily in realtime scenario, We should explore and optimize wherever we can.
I feel like some common String usage like split() or replaceAll() can be further optimized by pre compiling the regex.

```java
... 
static String[] splitToken(String token) throws JWTDecodeException {
        String[] parts = token.split("\\.");
...
```

It can be improvement by holding on Pattern.compile(regex) object and reusing it to call split() on this precompiled pattern object.

### What was the expected behavior?

same as before however minor improvement can be observed.

### Reproduction
N/A

### Environment

- **Version of this library used:**
- **Version of Java used:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by lbalmaceda** [comment]
With the only change that `splitTokenPattern` now makes use of a previously defined _final_ Pattern

```java
static final Pattern pattern = Pattern.compile("\\.");

static String[] splitTokenPattern(String token) throws JWTDecodeException {
    String[] parts = pattern.split(token);
    // ....
```

I wrote a quick snippet to test this out, and used 2 different JWTs (one short / one long) and different number of runs:

```java
System.out.println(String.format("=== %d attempts with short JWT (%d chars) ===", AMOUNT, shortToken.length()));
long startTime = System.nanoTime();
for (int i = 0; i < AMOUNT; i++) {
    TokenUtils.splitToken(shortToken);
}
long endTime = System.nanoTime();
long timeElapsed = endTime - startTime;
System.out.println("Regex- Execution time (ms): " + timeElapsed / 1000000);
```

#### Results

1k
```
=== 1000 attempts with short JWT (100 chars) ===
Regex- Execution time (ms): 5
Pattern- Execution time (ms): 6
=== 1000 attempts with long JWT (4256 chars) ===
Regex- Execution time (ms): 0
Pattern- Execution time (ms): 5
```

10k

```
=== 10000 attempts with short JWT (100 chars) ===
Regex- Execution time (ms): 16
Pattern- Execution time (ms): 47
=== 10000 attempts with long JWT (4256 chars) ===
Regex- Execution time (ms): 8
Pattern- Execution time (ms): 30
```

10M
```
=== 10000000 attempts with short JWT (100 chars) ===
Regex- Execution time (ms): 1970
Pattern- Execution time (ms): 5379
=== 10000000 attempts with long JWT (4256 chars) ===
Regex- Execution time (ms): 1531
Pattern- Execution time (ms): 5538
```

As seen above, having a constant `Pattern` actually makes it take longer than with a runtime defined `Regex`.

If you can provide something like the above proving that I'm wrong, I'm happy to review a suggested fix. Cheers

**Comment by jimmyjames** [comment]
Closing this issue per @lbalmaceda's findings above.
