### ISSUE TITLE
Support the "zip" property in JWT  header

### ISSUE THREAD

**Issue by grahamegrieve** [auth0/java-jwt#515]
I'd like the library to support the zip header defined in https://datatracker.ietf.org/doc/html/rfc7516#section-4.1.3

The ideal solution is that the library automatically un-deflates the content when the hard has "zip" : "DEF"

The only alternative it to roll my own local code

**Comment by grahamegrieve** [comment]
if ("DEF".equals(header.get("zip"))) {
      payloadJson = inflate(payloadJson);
    }
    
 and 
    

  public static final byte[] inflate(byte[] data) throws IOException, DataFormatException {
    final Inflater inflater = new Inflater(true);
    inflater.setInput(data);

    try (final ByteArrayOutputStream outputStream = new ByteArrayOutputStream(data.length))
    {
        byte[] buffer = new byte[BUFFER_SIZE];
        while (!inflater.finished())
        {
            final int count = inflater.inflate(buffer);
            outputStream.write(buffer, 0, count);
        }

        return outputStream.toByteArray();
    }
  }

**Comment by lbalmaceda** [comment]
@grahamegrieve Thanks for the interest. This library implements https://tools.ietf.org/html/rfc7519. Support for that header claim or the ability to decompress the content is not going to be added, as we attempt to stay aligned to what Auth0 supports or makes use of for authentication.
