### ISSUE TITLE
Support for EdDSA signing

### ISSUE THREAD

**Issue by Pranavb333** [auth0/java-jwt#518]
### Problem
Are EdDSA signatures going to be supported? Even PyJWT supports it (https://pyjwt.readthedocs.io/en/stable/algorithms.html).

JDK has added support for EdDSA (https://openjdk.java.net/jeps/339).

**Comment by jimmyjames** [comment]
Thanks @Pranavb333 for raising. We're going to take a look at support for EdDSA in this library and others. We'll follow-up here (FYI may be after the new year)

**Comment by jimmyjames** [comment]
As noted, this isn't supported by JDK < 15. As this library supports Java 8, this isn't something we're going to take on now. I'll keep an eye on this issue in case anyone wants to see if there's a way to add support in a way that won't break Java < 15 usages, if that's possible without requiring more extensive changes.

**Comment by jmanico** [comment]
You can get EdDSA support from bouncy castle now...
