### ISSUE TITLE
Support java.time instead of or alongside java.utils.date

### ISSUE THREAD

**Issue by Lalaluka** [auth0/java-jwt#522]
### Describe the problem you'd like to have solved
The library still uses java.utils.date instead of the newer java.time API
A change towards java.time or support alongside utils.date would be great for developer convenience.

### Describe the ideal solution
Something similar to #392

### Alternatives and current work-arounds
--

### Additional information, if any
I have seen that there have been questions about this feature in the past. But the last activity on the Topic has been in late 2020 and the Version4 Branch seems to be inactive for some time. So I took the freedom to create a new Issue, sorry if there are any external resources I overlooked. I think #421 also shines a good light on the topic.

**Comment by jimmyjames** [comment]
Thanks @Lalaluka! We may be able add newer java.time APIs alongside the existing Date APIs in the current release stream, by adding some new methods to the various interfaces to support new APIs that have a default implementation. I can explore this further; anyone willing to try it out once I have something? Thanks!

**Comment by Lalaluka** [comment]
Of course!
If it helps I'm happy to test/review once you have something :)
