### ISSUE TITLE
Unable to deserialize Claims of Lists with polymorphic types

### ISSUE THREAD

**Issue by davidgodzsak** [auth0/java-jwt#529]
### Describe the problem

I am unable to deserialize Claims of Lists with polymorphic types. I have a list of arguments that I am trying to pass into the JWT token as a claim. This list contains subclasses of a parent/generic class with a discriminator field.

### What was the expected behavior?

When I call `decodedToken.getClaim("poly_arguments").asList(Poly.class)`, I expect to get the list with the items deserialized. Instead I get an error `saying: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'child1' as a subtype of 'example.Poly': known type ids = []`

### Reproduction

Here is how I create the polymorphic types (I am using Kotlin but that is irrelevant, and I am adding the Jackson annotations, as I see your library is also using jackson so I hoped it would use the type info for that, which does not seem to be the case)
```
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type")
    sealed class Poly(val type: String)

    @JsonTypeName("child1")
    data class Child1(val foo: String): PolyParent("child1")
    
    @JsonTypeName("child2")
    data class Child2(val foo: String): PolyParent("child2")
```

Here is how I create my JWT token:
```
   val arguments = listOf(Child1("bar"), Child2("bar"))
   JWT.create()
                .withIssuer(ISSUER)
                .withSubject(ROUTING_SUBJECT)
                .withExpiresAt(Date.from(Instant.now().plus(1, ChronoUnit.HOURS)))
                .withPayload(mapOf("poly_arguments" to pokoToPrimitives(arguments))) 
                .sign(algorithm)

    private fun pokoToPrimitives(arguments: List<Poly>): List<*> =
        objectMapper.convertValue(arguments, List::class.java)

```
(Note:  I needed to serialize my data with `pokoToPrimitives`, where I am using a jackson objectMapper to do the job, as the library won't accept Pojos or Pokos, I think since you already use Jackson this could be also allowed, even better if the serialization could be configured or customized, see proposals for solution)

Then I want to deserialize the JWT token where I use it:
```
           val verifier = JWT.require(algorithm)
              .withIssuer(ISSUER)
              .withSubject(ROUTING_SUBJECT)
              .build()

           verifier.verify(token).claims["poly_arguments"].asList(Poly::class.java)
```

I get an error `saying: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'child1' as a subtype of 'example.Poly': known type ids = []`

What this tells me is that you use Jackson, however for some reason that does not read the annotations attached to the polymorphic types, maybe the ObjectMapper is configured wrong. 

### Proposals for Solution

1. I think as a solution you should either fix that, or make sure that your implementation of the `.asList()` is able to read polymorphic lists (I think this would be a problem with maps or too that also allow generics).
2. The root of the problem is also that you don't allow any ways to configure the serialization/deserialization of the claims. That could be solved in multiple ways: either allow to configure your internal ObjectMapper, or even better add a way to include custom Json serializer/dereializer, or interfaces for serialization/deserializaton, or even the abilty to get the claim data out raw and let the user do whatever they want with it.

### Environment

- **Version of this library used:** 3.18.2
- **Version of Java used:** 11
- **Other modules/plugins/libraries that might be involved:** jackson

**Comment by poovamraj** [comment]
Hi @davidgodzsak, I was able to fix this issue by registering your types in the following way

```kotlin
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type")
    @JsonSubTypes(
            JsonSubTypes.Type(name = "child1", value = Child1::class),
            JsonSubTypes.Type(name = "child2", value = Child2::class)
    )
    sealed class Poly(val type: String)

    data class Child1(@JsonProperty("foo") val foo: String): Poly("child1")

    data class Child2(@JsonProperty("foo") val foo: String): Poly("child2")
```

Hope this helps.

Regarding exposing the Jackson Mapper. We will consider this use case internally and if the team agrees, will implement it in the upcoming Major.

I am closing this ticket since the issue seems to be resolved. Please feel free to reopen this if you have any more doubts regarding this.
