### ISSUE TITLE
Empty JWT values do not work as expected

### ISSUE THREAD

**Issue by Foyerwehr** [auth0/java-jwt#548]
### Describe the problem
Empty JWT values do not work right now as expected from the rfc7519. The rfc7519 defines in section 10.3.1 "Encoding considerations", where empty string values are allowed. 

### What was the expected behavior?
The expected behavior would be that emty values in the JWT are valid. 

If the protected-header or the payload is empty, I would expect that we get a valid DecodedJWT where some claims are not available.
An empty signiture and how to handle them is up for discussion.
I personally work only with signed JWTs.
### Reproduction

- Take for example a JWT with an empty payload. 
-> This will result in an exception:
```
com.auth0.jwt.exceptions.JWTDecodeException: The string '' doesn't have a valid JSON format.
	at com.auth0.jwt.impl.JWTParser.decodeException(JWTParser.java:75)
	at com.auth0.jwt.impl.JWTParser.parsePayload(JWTParser.java:38)
	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:48)
	at com.auth0.jwt.JWT.decodeJwt(JWT.java:32)
```

### Environment

- **Version of this library used:** java-jwt-3.18.3
- **Version of Java used:** 8
- **Other modules/plugins/libraries that might be involved:** none
- **Any other relevant information you think would be useful:**
https://datatracker.ietf.org/doc/html/rfc7519#section-10.3.1

This is my first issue report. If I can improve anything, please let me know.

**Comment by poovamraj** [comment]
Hi @Foyerwehr, Thanks for the suggestion. We will have an internal discussion regarding supporting this and update you here.

**Comment by jimmyjames** [comment]
@Foyerwehr can you provide an example of a JWT payload to demonstrate? Is it handled how you'd expect when using the debugger on [https://jwt.io](https://jwt.io)? 

In section 7.2 of the RFC, it states:

> Verify that the resulting octet sequence is a UTF-8-encoded representation of a completely valid JSON object conforming to [RFC 7159](https://datatracker.ietf.org/doc/html/rfc7159); let the JWT Claims Set be this JSON object.

When I try and decode a JWT with an empty string as the claim set on jwt.io, I get a warning message referring to this section of the RFC. So, it seems we'll need to understand the potential discrepancy between what you referenced in section 10.3.1 and section 7.2.

**Comment by abhishekbhat004** [comment]
Hi @jimmyjames,
The latest ACME spec requires support for payloads with an empty string (""). 
(https://datatracker.ietf.org/doc/html/rfc8555#section-6.3)

Right now if I try to parse a payload with an empty string, I get an exception
com.auth0.jwt.exceptions.JWTDecodeException: The string '' doesn't have a valid JSON format.

**Comment by poovamraj** [comment]
Hi @Foyerwehr, we have taken a note of this feature to our backlog but since this is not in our near future roadmap, we are closing this issue for now. Please feel free to contribute to this feature or reopen this issue if you have more doubts
