### ISSUE TITLE
Add listener interface for detecting whether RSA keys have been rotated

### ISSUE THREAD

**Issue by skjolber** [auth0/java-jwt#559]
### Describe the problem you'd like to have solved
We operate a tenant with unique audiences per application. These applications also call on each other, each caching the JWTs for outgoing calls. So in a nutshell, the issuer is the same for in- and outgoing JWTs.

So it might happen that the JWKs are refreshed while we're holding a cached JWT. If the JWKs have been rotated since the cached token was issued, we would like to purge the cached JWT. 

### Describe the ideal solution
Add a "JWKs rotation" listener, or some kind of a "JWKs refreshed" listener.

## Alternatives and current work-arounds
Refresh token and retry once on HTTP 401 responses. Revalidate and optionally refresh token on HTTP 401 responses. 

### Additional information, if any
We might want to rotate all clients if the keys are rotated, even if not on the same tentant.

**Comment by skjolber** [comment]
@poovamraj I've updated the issue. This should be pretty trivial.

**Comment by jimmyjames** [comment]
Hi @skjolber, as this library does not handle JWK sets directly, and instead exposes the `KeyProvider` interface for implementation, can you expand on what specific addition you'd like added to this library? Perhaps a code snippet or proposal would help us evaluate this request better. Thanks!

**Comment by poovamraj** [comment]
@skjolber We are closing this issue for now as we need more details to start analyzing this. Please feel free to reopen this ticket and we will be happy to help.
