### ISSUE TITLE
Support for RS256

### ISSUE THREAD

**Issue by mpaktiti** [auth0/java-jwt#56]
The JWT Java library at https://github.com/auth0/java-jwt/blob/master/src/main/java/com/auth0/jwt/JWTVerifier.java currently does not support RS256.

It should be updated in order to support this.

The issue was raised at ticket [6605](https://auth0.zendesk.com/agent/tickets/6605)

**Comment by arcseldon** [comment]
@mpaktiti - thanks for raising this issue. Support is now provided.
