### ISSUE TITLE
Unable to verify JWT without secret key

### ISSUE THREAD

**Issue by quintonn** [auth0/java-jwt#563]
I want to validate a JWT's signature without the secret key, just like https://JWT.IO does it.  

But the code does not seem to allow that.  

This is the code I tried:  

```java
                        final String token = "eyJ....";
			final DecodedJWT jwt = JWT.decode(token);
			
			Algorithm algorithm = Algorithm.HMAC512((String)null);
			algorithm.verify(jwt);
			final JWTVerifier verifier = JWT.require(algorithm).build();
			final DecodedJWT decodedJwt = verifier.verify(token);
			final String encodedHeader = decodedJwt.getHeader();
			System.out.println(encodedHeader);
```

I am trying two methods sort of, but it doesn't get past the algorithm setup line.  

I have to provide the same key for this code to work. Which doesn't seem correct.

**Comment by poovamraj** [comment]
Hi @quintonn, As you can see in jwt.io, The secret key is used based on the algorithm. It is just prefilled with a sample key. You can find this under the "VERIFY SIGNATURE" section.

Can you provide more details on the use case you are trying to achieve here? Verifying just the claims without the algorithm isn't possible currently using the library.

**Comment by quintonn** [comment]
Well part of the JWT spec is to be able to verify that a JWT has not been tampered with.
With certificates that is done using the public key, which makes sense.
But when a JWT is signed with a secret, it should still be possible to verify the signature without actually having the secret key used to create the token.
But that does not seem possible with this library.
Or am I missing something?

And in JWT.IO I can paste a token created on my own computer with my own secret key, and yet JWT.IO is able to verify the signature **without** the secret key.

**Comment by poovamraj** [comment]
Hi @quintonn, Can you share what algorithm is used to create this JWT? Also a sample/reproduction with *sample secrets* would really help us understand the issue.

**Comment by quintonn** [comment]
Below  is the code to sign and verify the JWT:

**But, as you can see, in order to validate/verify the token, I need the password.  
How can I do this without having to know the password??**  

And this should be possible, because if I paste the token into JWT.io, it is able to verify my signature without knowing the secret key.  

```java
final Algorithm signingAlgorithm = Algorithm.HMAC512("password");

final Builder builder = JWT.create();// .withHeader(headerClaims);
// this is just a list obtained somewhere else

// addClaims(builder); // handled somewhere else, not important
builder.withClaim("age", 65);

final String token = builder.sign(signingAlgorithm);

final Algorithm algorithm = Algorithm.HMAC512("password"); // How to not have to pass the password here? 
              //  Since clients won't have the password ?????
final DecodedJWT jwt = JWT.decode(token);

System.out.println("verifying");
algorithm.verify(jwt);
System.out.println("Verified");
final JWTVerifier verifier = JWT.require(algorithm).build();
final DecodedJWT decodedJwt = verifier.verify(token);

System.out.println(decodedJwt.getClaim("any_thing").asString());
System.out.println(decodedJwt.getClaim("name").asString());
System.out.println(decodedJwt.getClaim("age").asInt());
System.out.println(decodedJwt.getHeaderClaim("exp").asString());
```

**Comment by poovamraj** [comment]
@quintonn HMAC should be used when the client can be maintained as a secret between all the token users. In the case of public clients, RSA or ECDSA are more suitable.

Verifying a token without its public key cannot verify whether the token has been tampered with (Signature verification). This is not recommended as it is highly insecure.

jwt.io uses the secret already provided in the "Decoded" section to verify the signature's integrity. You can check this by changing the signature part of the generated token, you get "Invalid Signature" error.

You can read this page for more information on JWT - https://jwt.io/introduction

**Comment by quintonn** [comment]
Ok, I think I get it.
The HMAC should only be used if the secret is known when signing and verifying the token, such as on an authorization server or similar.
But for verifying a token signed by someone else, one of the other algorithms should be used where public/private keys are used??

I think in that case you can close this ticket.

Thank you for helping me with this, I thought even the HMAC algorithms should have been verifiable without the secret.

**Comment by poovamraj** [comment]
Happy to help :) Feel free to reopen this issue if you have any more doubts. Closing this for now.
