### ISSUE TITLE
com.auth0.jwt.exceptions.JWTDecodeException: The input is not a valid base 64 encoded string.

### ISSUE THREAD

**Issue by Junesui** [auth0/java-jwt#567]

**Comment by Junesui** [comment]
![image](https://user-images.githubusercontent.com/53398033/160272487-e3cfe0f3-733c-4b2f-8316-51f82657d140.png)

**It seems that there is an error because there is a double quotation mark here.**

**Comment by Junesui** [comment]
The front-end page has a double quotation mark when passing the value 。 already solved it。 
close

**Comment by StefanSchubert** [comment]
Hi what was the solution in this case?
