### ISSUE TITLE
Nested Claims

### ISSUE THREAD

**Issue by overheadhunter** [auth0/java-jwt#586]
### Describe the problem you'd like to have solved

For both header and payload, a key may contain an object as its value, as shown for `foo` in this example:

```json
{
  "sub": "1234567890",
  "name": "John Doe",
  "iat": 1516239022,
  "foo": {
    "bar": true,
    "baz": [{"value": 23}, {"value": 42}]
  }
}
```

I'm looking for a convenient way to access the values for `bar` or `baz`.

### Describe the ideal solution

Please add a `Claim asClaim()` method (suitable for `foo`) and `Claim[] asClaims()` (suitable for `foo.baz`). Basically every sub-object conforms to the `Claim` API itself.

If called on a non-object, throw a `JWTDecodeException` as with the other methods.

### Alternatives and current work-arounds

At least for top-level objects (`foo`), the current API offers two related methods:

https://github.com/auth0/java-jwt/blob/f87a5d3f7ce0df3c428fc16e72f2f27659dcf6be/lib/src/main/java/com/auth0/jwt/interfaces/Claim.java#L112-L129

Both are suboptimal: The former loses any type information and the latter requires me to define a type myself.

Furthermore for nesting levels > 1 (`foo.baz`), they don't help.

### Additional information, if any

~nope~ edit: oh if PRs are welcome, I'd like to give this a shot

**Comment by poovamraj** [comment]
Hi @overheadhunter, At this point, we don't see ourselves supporting this API but we will take a note of it and based on future requests, we can consider taking it up. Sorry about it.

Hopefully, the `<T> T as(Class<T> clazz)` method supports your use-case though.
