### ISSUE TITLE
Support for payloads with an empty string

### ISSUE THREAD

**Issue by abhishekbhat004** [auth0/java-jwt#588]
Can payloads with empty string be handled?
The latest ACME specification requires support for payloads with an empty string ("").
(https://datatracker.ietf.org/doc/html/rfc8555#section-6.3)

Right now if I try to parse a payload with an empty string, I get an exception
com.auth0.jwt.exceptions.JWTDecodeException: The string '' doesn't have a valid JSON format.

**Comment by poovamraj** [comment]
Hi @abhishekbhat004, can you provide a sample JWT?

**Comment by abhishekbhat004** [comment]
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vc2VydmVyMS5xYS5lbXVkaHJhLm5ldC9lbVNpZ25BQ01FLUFQSS9hY21lL2FjY3QvMzFmZmI0MGItNjJhZS00NzY2LTkzYTYtYjg4MTMxYTJlZjY5IiwgIm5vbmNlIjogIjM4OTY4NWE5LWEwZjYtNDUyZi05ODg0LWEyYTU3ZGFhNzUxNSIsICJ1cmwiOiAiaHR0cHM6Ly9zZXJ2ZXIxLnFhLmVtdWRocmEubmV0L2VtU2lnbkFDTUUtQVBJL2FjbWUvYXV0aHovMDYwYzcwZmUtNmRmYy00MDY3LWI4YTctMzU3ZWIxNDM2Yzg2In0",
  "signature": "shpk-LlGuzjFkbQmU1tF10cP6vbIsIZtWhkjpjIzkWorx1pjhDYXt2EVZHWkQdccOCuBbo4siq6zLmsOcpGmKcZXMiTo7B9QCTN9QNS9-u0rEtBhDU8R3QstOwFNm6wdRfRReSnoHq7nmUfCG4e9aQNN5EpsjNcgr_qwlUn_HadORkdT918YtvqkeABNm8ivBmWWyMDKKEzz5vs2CcZozOUe5fRXajKWmDmCzqviqXNVSbJC_jUe1iGzDmCdSTh5LmIVsWzxNO4Y92OewI8l7TvPI30N5ysujf7j_DpwNK7S-512yNrxGsNzpf2fcclX4mULwxLvRNjIhqQSv_42gA",
  "payload": ""
}

**JWT**
eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vc2VydmVyMS5xYS5lbXVkaHJhLm5ldC9lbVNpZ25BQ01FLUFQSS9hY21lL2FjY3QvMzFmZmI0MGItNjJhZS00NzY2LTkzYTYtYjg4MTMxYTJlZjY5IiwgIm5vbmNlIjogIjM4OTY4NWE5LWEwZjYtNDUyZi05ODg0LWEyYTU3ZGFhNzUxNSIsICJ1cmwiOiAiaHR0cHM6Ly9zZXJ2ZXIxLnFhLmVtdWRocmEubmV0L2VtU2lnbkFDTUUtQVBJL2FjbWUvYXV0aHovMDYwYzcwZmUtNmRmYy00MDY3LWI4YTctMzU3ZWIxNDM2Yzg2In0..shpk-LlGuzjFkbQmU1tF10cP6vbIsIZtWhkjpjIzkWorx1pjhDYXt2EVZHWkQdccOCuBbo4siq6zLmsOcpGmKcZXMiTo7B9QCTN9QNS9-u0rEtBhDU8R3QstOwFNm6wdRfRReSnoHq7nmUfCG4e9aQNN5EpsjNcgr_qwlUn_HadORkdT918YtvqkeABNm8ivBmWWyMDKKEzz5vs2CcZozOUe5fRXajKWmDmCzqviqXNVSbJC_jUe1iGzDmCdSTh5LmIVsWzxNO4Y92OewI8l7TvPI30N5ysujf7j_DpwNK7S-512yNrxGsNzpf2fcclX4mULwxLvRNjIhqQSv_42gA

**Comment by poovamraj** [comment]
Hi @abhishekbhat004, This seems like a useful feature and since it is already requested in #548 would you be open to submitting a PR for this. We would be happy to guide you through it.

**Comment by poovamraj** [comment]
Hi @abhishekbhat004 we have noted this down in our backlog but since this in not in our priority in near future we are closing this issue. Please feel free to contribute to this feature or reopen this issue for more doubts.
