### ISSUE TITLE
How to sign and verify using HS512

### ISSUE THREAD

**Issue by nostalgiatune** [auth0/java-jwt#59]
Does this library support signing with HS512? Also, what is the actual difference to HS256?

**Comment by rafass90** [comment]
Hi @nostalgiatune ,

Yes, it does.

`
Options opt = new Options();
opt.setAlgorithm(Algorithm.HS512);
final String token = signer.sign(claims, opt);
`

The difference is basically the hash's size. 512 bits for HS256 and 1024 for HS512 and HS384.
