### ISSUE TITLE
pass "iat" or "eat" as string or long value 

### ISSUE THREAD

**Issue by MTayyabSarfraz** [auth0/java-jwt#591]
Wouldn't it be better to give the option to pass `issuedAt`/`expiredAt` as long(milisec) rather than parsing it to date first?
Will reduce the developer's effort!

**Comment by poovamraj** [comment]
Hi @MTayyabSarfraz we have consciously taken a step to not provide this API as it could cause confusion (Especially accepting string type). Our latest library also accepts `Instant` which has a much neater API that you can use. Hope that help. Please feel to reopen this issue if you have more doubts
