### ISSUE TITLE
JWKStore still unclear

### ISSUE THREAD

**Issue by purejgleason** [auth0/java-jwt#599]
basically an extension of this question (https://github.com/auth0/java-jwt/issues/285)

I am trying to follow the JWKStore example I have tried to search for the Javadoc for the project `JWKStore` in the repo `https://github.com/auth0/jwks-rsa-java` but I still can't find it. Intellij IntelliSense also can't find it after importing the library.

**Comment by poovamraj** [comment]
Hi, The JWKStore mentioned in the document is an "imaginary" implementation and I can see why it can be confusing. We have updated the README with a sample from our JWKS library which can be used for simple purposes - https://github.com/auth0/java-jwt/pull/600

Do let us know if you have more doubts about this
