### ISSUE TITLE
Does JDK1.6 support?

### ISSUE THREAD

**Issue by gitaxin** [auth0/java-jwt#601]
I want to use this package in JDK1.6 environment, which version supports it?

I have the following error when using it in JDK1.6:

 `java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/auth0/jwt/JWT, offset=`

**Comment by poovamraj** [comment]
Hello @gitaxin, this library currently supports all Java 8, 11 & 17. We currently do not support Java 1.6 as many of the APIs we have are not supported in it.

**Comment by gitaxin** [comment]
allright,Thanks!
