### ISSUE TITLE
Make RegisteredClaims values constants

### ISSUE THREAD

**Issue by an-kcu** [auth0/java-jwt#603]
### Describe the problem you'd like to have solved

I would like to use the values defined in `RegisteredClaims` (and potentially `HeaderParams`) as annotation values, for example to model a JWT (full or just payload) using a custom class. Currently, the values defined in these classes are not marked `final` and therefore cannot be used in annotation values. As far as I can tell, there is no case where they need to be mutable, and it seems to me that these are intrinsically constant values.

### Describe the ideal solution

Make all values defined in `RegisteredClaims` and `HeaderParams` `final` so that they can be used in annotation values. I'm happy to submit a PR, especially if this is the extent of the changes.

### Alternatives and current work-arounds

Either finding an additional library that has these values, or redefining them as constants within my project.

### Additional information, if any

`java-jwt:4.0.0`

**Comment by poovamraj** [comment]
Hi @an-kcu, Thanks for raising this. It is a very valid request and we have raised a PR with this change - https://github.com/auth0/java-jwt/pull/604

I will close this issue for now but feel free to reopen it if you have any more doubts about this.
