### ISSUE TITLE
Why am I getting "signature verification failed"?

### ISSUE THREAD

**Issue by runmael** [auth0/java-jwt#61]
Hi, it seems I am missing something. I have copied example from the README, but when I do the following:

     final String secret = "secret";

     final long iat = System.currentTimeMillis() / 1000l; // issued at claim
     final long exp = iat + 172800L; // +48 hours

     final JWTSigner signer = new JWTSigner(secret);
     final HashMap<String, Object> claims = new HashMap<String, Object>();
     claims.put("exp", exp);
     claims.put("iat", iat);

     final String jwt = signer.sign(claims);
     final JWTVerifier verifier = new JWTVerifier(secret);
     final Map<String,Object> zz = verifier.verify(jwt);

I get `java.security.SignatureException: signature verification failed`. What am I missing? Thank you for you help!

EDIT: I checked my version, and it seems I am using an older one (1.0.0), is it safe to upgrade to 2.2.0?
EDIT2: I am getting same error on v2.2.0

EDIT3: It seems that JWTVerifier needs Base64 encoded secret, can anyone confirm this?

**Comment by pocman** [comment]
I had the same issue.
Using the same token and secret, I can successfully verify with https://jwt.io/ (after hitting "secret base64 encoded") but not with a small worksheet: 

```
import com.auth0.jwt._
import org.apache.commons.codec.binary.Base64

val secret = "my_secret_from_auth0"
val jwt = "my_token"

val verifier: JWTVerifier = new JWTVerifier(secret) //Not working
verifier.verify(jwt)
```

```
val verifier: JWTVerifier = new JWTVerifier(new Base64().decode(secret)) //Working
verifier.verify(jwt)
```

**Comment by rafass90** [comment]
Hi @runmael , 

Use 
         `new JWTSigner(new Base64(true).decodeBase64(clientSecret));` 
  instead of 
         `new JWTVerifier(secret)`
