### ISSUE TITLE
Claim asString returns null for types with valid string representations

### ISSUE THREAD

**Issue by worthc21** [auth0/java-jwt#614]
### Describe the problem
getClaim("X").asX returns null for values that have valid toString representations

When creating a private claim with an integer value - 
`withClaim("ID", 1234)`
the decoded JWT
`getClaim("ID").asString()`
returns null

When creating a private claim with a boolean value - 
`withClaim("flag", true)`
the decoded JWT
`getClaim("flag").asString()`
returns null

### What was the expected behavior?
An integer value would return the string representation of the value (just as Integer.toString() does)
A boolean value would return the string representation of the value (just as Boolean.toString() does)

### Versions
java-jwt: 4.0.0
java - JDK 11
spring boot - 2.7.4

**Comment by jimmyjames** [comment]
Thanks for raising @worthc21. Yes, that is the expected behavior, as we first check that the node is textual. For the string value, you can use `toString()`. Hope that helps!

**Comment by jimmyjames** [comment]
I updated the javadocs in #615 to be more accurate with the actual behavior. Thanks!

**Comment by worthc21** [comment]
Nice - thanks for taking the time to address!

**Comment by kelalaka153** [comment]
I did not find this to be a good idea. Why can't we have the claim just as a string instead we get the null? The programmer decides to have it as a raw string or not. Instead, the library forces it to parse as .asObject(PoJo::class.java).
