### ISSUE TITLE
Support verification for anyOfClaim

### ISSUE THREAD

**Issue by jlorenzen** [auth0/java-jwt#623]
### Describe the problem you'd like to have solved

It would be extremely useful if the [Verification](https://github.com/auth0/java-jwt/blob/02c9d168e2af4a20b13028c3083212eed72ac399/lib/src/main/java/com/auth0/jwt/interfaces/Verification.java) interface supported the ability to verify whether any JWT claim contains a value from a list of expected values.

### Describe the ideal solution

Ideally a verification method similar to [withAnyOfAudience](https://github.com/auth0/java-jwt/blob/02c9d168e2af4a20b13028c3083212eed72ac399/lib/src/main/java/com/auth0/jwt/interfaces/Verification.java#L61) but for any claim. Specifically we need this to verify the `client_id` claim contains a value from a list of values.

For example:
```java
JWT
  .require(algorithm)
  .withAnyOfClaim("client_id", "clientIdValue1", "clientIdValue2")
  .build()
```

### Alternatives and current work-arounds

1. Similar feature request to #474
2. Attempted to see if I could add a kotlin extension function, but the [BaseVerification.expectedChecks](https://github.com/auth0/java-jwt/blob/02c9d168e2af4a20b13028c3083212eed72ac399/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L57) variable is private
3. Considered extending [BaseVerification](https://github.com/auth0/java-jwt/blob/02c9d168e2af4a20b13028c3083212eed72ac399/lib/src/main/java/com/auth0/jwt/JWTVerifier.java#L55), but that's not really useful as it's locked down tightly as well
4. As suggested in #474, might have to perform custom verification after calling `JWTVerifier.verify`. Would work but not ideal.

### Additional information, if any

1. If support was added for this method, I could see the existing `withAnyOfAudience` calling it as it's the same type of check just with a different claim.
1. This requirement has become increasingly necessary as our API is verifying JWTs from different clients that are using the OAuth2 `client_credentials` flow.

I'd be happy to submit a PR if this feature request was deemed a worthy addition to the existing API.

**Comment by jimmyjames** [comment]
👋 hi @jlorenzen, thanks for the details. 

In v4 we added the ability to verify a claim using a provided `Predicate`, so that verifications such as your use case can be accommodated. A simple test to demonstrate:

```java
@Test
public void shouldSuccessfullyVerifyClaimWithPredicate2() {
    List<String> listClaim = Arrays.asList("one", "two");

    String jwt = JWTCreator.init()
            .withClaim("listClaim", listClaim)
            .sign(Algorithm.HMAC256("USE-BETTER-SECRET"));

    JWTVerifier verifier = JWTVerifier.init(Algorithm.HMAC256("USE-BETTER-SECRET"))
            .withClaim("listClaim", (claim, decodedJWT) -> claim.asList(String.class).contains("one"))
            .build();

    DecodedJWT decodedJWT = verifier.verify(jwt);
    assertThat(decodedJWT, is(notNullValue()));
}
```

**Comment by jlorenzen** [comment]
@jimmyjames That's perfect! I can't believe I didn't see that. Thanks
