### ISSUE TITLE
Gradle dependency definition in docs is incorrect

### ISSUE THREAD

**Issue by donalmurtagh** [auth0/java-jwt#63]
There should be a colon between the group ID and the artefact ID, i.e.

    compile 'com.auth0:java-jwt:2.2.0'

instead of

    compile 'com.auth0.java-jwt:2.2.0'

**Comment by arcseldon** [comment]
@donalmurtagh - thanks for pointing this out.

[PR raised](https://github.com/auth0/java-jwt/pull/65)
