### ISSUE TITLE
Match compile and runtime versions of jackson library dependency.

### ISSUE THREAD

**Issue by adakeles** [auth0/java-jwt#639]
The dependency 
`com.fasterxml.jackson.core:jackson-databind`
seems to have inconsistent versions between runtime and compile when using java-jwt 4.2.1.

Expected result:
```
\- com.fasterxml.jackson.core:jackson-databind:jar:2.13.4.2:runtime
   +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:runtime
...
+- com.auth0:java-jwt:jar:4.2.1:compile
\- com.fasterxml.jackson.core:jackson-databind:jar:2.13.4.2:compile
```
Actual result:
```
\- com.fasterxml.jackson.core:jackson-databind:jar:2.13.4.2:runtime
   +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.4:runtime
...
+- com.auth0:java-jwt:jar:4.2.1:compile
\- com.fasterxml.jackson.core:jackson-databind:jar:2.13.3:compile  <------ Inconsistent with runtime. Expected to be 2.13.4.2
```

**java-jwt version used: 4.2.1**

Related issue: [624](https://github.com/auth0/java-jwt/issues/624)
Related issue: [jackson-databind 3582](https://github.com/FasterXML/jackson-databind/issues/3582)

**Comment by jimmyjames** [comment]
👋 hi @adakeles, is it possible that you are including other dependencies which could be causing this issue? When I look at the dependencies of `auth0-java` (which uses this library), the dependencies appear to resolve as expected.

**Comment by jimmyjames** [comment]
Given that the Jackson dependency is implementation scoped, I don't see how this is an issue with this library, so closing this issue. If additional details are found that cause the issue, please share here so others are aware. Thanks!
