### ISSUE TITLE
Aud with empty string returns empty List

### ISSUE THREAD

**Issue by andrewrigas** [auth0/java-jwt#662]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/java-jwt#readme) and [Examples](https://github.com/auth0/java-jwt/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://javadoc.io/doc/com.auth0/java-jwt/latest/index.html) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/java-jwt/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When an audience with empty string pass to the payload when we try to decode it returns empty list instead of list with empty string. 

### Header
```json
{
  "alg": "none",
  "typ": "JWT"
}
```

### Payload
```json
{
  "aud": ""
}
```

### Reproduction

```scala
val token      = JWT.create().withAudience("").sign(Algorithm.none())
val decodedJWT = JWT.require(Algorithm.none()).build().verify(token)

// Also this issue expands to withAudience("") provided requirements on verification.

println(s"$token") // eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiIifQ.
println(s"** ${decodedJWT.getAudience}") // []
println(s"*** ${decodedJWT.getAudience.size()}") // 0
```

### java-jwt version

4.4.0

### Java version

Oracle Corporation Java 11.0.16.1

**Comment by jimmyjames** [comment]
Thanks for the info @andrewrigas!

You are correct; when the claim value is a string, it's only added to a singleton list if the value is not empty ([source](https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/impl/PayloadDeserializer.java#L57)).

The code has been there for over seven years, so I'd like to try and understand any specific use cases that it was added for before making any changes.

I'm curious, what is the use case with an empty audience string that caused you to encounter this?

**Comment by andrewrigas** [comment]
Hey @jimmyjames, 
No use case other than just the behaviour is unexpected when an empty string is inserted. I have property-base testing enabled in my tests and when I allow empty strings to be generated I get this error. I would like to see the reason but also this to get resolved. I tried instead reading it manually with API and still got into the same problem. So, its not just audience its a general bug with lists and single empty string.

**Comment by jimmyjames** [comment]
Thanks @andrewrigas, do you have another example of the same behavior with Lists and single empty strings behaving the same way?

**Comment by andrewrigas** [comment]
> Thanks @andrewrigas, do you have another example of the same behavior with Lists and single empty strings behaving the same way?

I am not able to reproduce it again. Maybe I was doing something wrong. So probably it's just `aud` claim.

**Comment by jimmyjames** [comment]
No worries, I'll take a look again, but I'm pretty sure the code in question is only used for the `aud` claim.

**Comment by andrewrigas** [comment]
@jimmyjames let me know if this is something that can be fixed, I can also help if needed.

**Comment by jimmyjames** [comment]
Hey @andrewrigas, I've made #663 to fix the issue, feel free to take a look (pretty simple change). Thanks!
