### ISSUE TITLE
Support for custom values in the header

### ISSUE THREAD

**Issue by mattalexx** [auth0/java-jwt#67]
https://tools.ietf.org/html/rfc7519#section-5.3

> 5.3.  Replicating Claims as Header Parameters
> 
> In some applications using encrypted JWTs, it is useful to have an
> unencrypted representation of some claims.  This might be used, for
> instance, in application processing rules to determine whether and
> how to process the JWT before it is decrypted.
> 
> This specification allows claims present in the JWT Claims Set to be
> replicated as Header Parameters in a JWT that is a JWE, as needed by
> the application.  If such replicated claims are present, the
> application receiving them SHOULD verify that their values are
> identical, unless the application defines other specific processing
> rules for these claims.  It is the responsibility of the application
> to ensure that only claims that are safe to be transmitted in an
> unencrypted manner are replicated as Header Parameter values in the
> JWT.

Can support be added for this?

**Comment by lbalmaceda** [comment]
Hi @mattalexx. Version 3 of the lib support this, check it out https://github.com/auth0/java-jwt/blob/master/lib/src/main/java/com/auth0/jwt/JWTCreator.java#L71
Cheers.
