### ISSUE TITLE
getting RunTimeException when signing with RS256

### ISSUE THREAD

**Issue by folol** [auth0/java-jwt#77]
This is how i am generating the token but i am getting RuntimeException . Please help.
I am generating this token for firebase custom auth. Custom token claims are given [here](https://firebase.google.com/docs/auth/server/create-custom-tokens)
I am doing this in android studio 2.1.3 and testing on a phone with android 4.1.2.

```
   `final String issuer = "abc-server@abc-gserviceaccount.com";
    final String sub = "abc-server@abc-gserviceaccount.com";
    final String aud =      "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit";
    final String secret = "ajksdfhfdasihdfasiudufashuifdhsuidfa";

    final long iat = System.currentTimeMillis() / 1000L; // issued at claim
    final long exp = iat + 60L; // expires claim. In this case the token expires in 60 seconds


    final JWTSigner signer = new JWTSigner(secret );
    final HashMap<String, Object> claims = new HashMap<String, Object>();
    claims.put("alg","RS256");
    claims.put("iss", issuer);
    claims.put("sub",sub);
    claims.put("aud",aud);
    claims.put("iat", iat);
    claims.put("exp", exp);
    claims.put("uid",number);

    JWTSigner.Options options = new JWTSigner.Options();
    options.setAlgorithm(Algorithm.RS256);


    final String jwtString = signer.sign(claims ,options );`
```

**Comment by arcseldon** [comment]
@folol - it looks like you are mixing `HS256` and `RS256` up. If you really want to use `RS256` - then take a look at this [test](https://github.com/auth0/java-jwt/blob/master/src/test/java/com/auth0/jwt/JWTRoundTripRsa256Test.java#L82)

If you are simply using `HS256` (secret as above being passed to JWTSigner) then you want to change the Algorithm accordingly.

**Comment by folol** [comment]
okay i got the point , that i have to give a PrivateKey to JWTSigner ,but the problem is that i am generating this token for Firebase custom auth and it gives me a private key as a String to sign token with it , so that it can verify it later , can you (@arcseldon) sir please  tell me how can i convert that String into a PrivateKey object or if there is any other method to do so?

**Comment by lbalmaceda** [comment]
Hi @folol. The keys are usually base64 encoded, so you'll need to decoded them first.

Example RSA public key without the headers:
```java
String keyString =
            "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv96lCis0QPEB7sHRiZ5m" +
            "HAlFrjuiUuKk3Lmt76cbwX21SF5c40PT50BC9ZJgfj834pvOut0dNcMF/dzQ80uC" +
            "yUwL3NjGR+SxUkJ0J9sKFeZLNwS5zrJi9HB5DeDXw3jTnMvOxIMMzSpf1KoQtyw7" +
            "03qVNw6nfSyywjtLUbCWKvPuKSG/l3bbSPX+vdqb5NmDlA+afUa00FaxL9vBh49F" +
            "8K+WZSsnE5xl94yXfEczScmihlxgGJUz2KTU3LM9Afwv7O0iBEo9yLnLgQZT+Sdm" +
            "bbO9Sjb7KfhAOgjF71pZaZl6zm2XA9fRlj9zHaY0uYwtQqXPRIGd79ZSi2Yfmi0l" +
            "hwIDAQAB";
```

Then I read the String and create the instance.

```java
//get bytes
byte[] bytes = keyString.getBytes("UTF-8")

//base64 decode
byte[] decoded = Base64.decodeBase64(bytes);

//create the key instance
PublicKey publicKey = null;
        try {
            KeyFactory kf = KeyFactory.getInstance("RSA");
            EncodedKeySpec keySpec = new X509EncodedKeySpec(decoded);
            publicKey = kf.generatePublic(keySpec);
        } catch (Exception e) {
            //check cause
            System.out.println("Could not reconstruct the public key");
        }

//use publicKey
```
I hope it helps. 

Cheers
