### ISSUE TITLE
JWTVerifier does not take 'algorithm' parameter

### ISSUE THREAD

**Issue by peraxel** [auth0/java-jwt#82]
As discussed in a blog post on auth0.com we need to be able to specify algorithm when verifying JWT signature. This library currently does not implement that. Please add an 'algorithm' parameter to JWTVerifier (constructor or 'verify' method).

Link to blog post: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by lbalmaceda** [comment]
Hi @peraxel. 
This is not supported in v2 as it only verifies HS256 and RS256. But we have released a new major version that supports more Algorithms and also fixes this issue. Please check it out, currently the latest version is `3.0.2`.

Cheers
